// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IAdminImpersonationLogRepository is an autogenerated mock type for the IAdminImpersonationLogRepository type
type IAdminImpersonationLogRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, tx, log
func (_m *IAdminImpersonationLogRepository) Create(ctx context.Context, tx *gorm.DB, log *entity.AdminImpersonationLog) error {
	ret := _m.Called(ctx, tx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.AdminImpersonationLog) error); ok {
		r0 = rf(ctx, tx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EndSession provides a mock function with given fields: ctx, tx, id
func (_m *IAdminImpersonationLogRepository) EndSession(ctx context.Context, tx *gorm.DB, id uuid.UUID) error {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for EndSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindActiveSessions provides a mock function with given fields: ctx, tx, adminUserID
func (_m *IAdminImpersonationLogRepository) FindActiveSessions(ctx context.Context, tx *gorm.DB, adminUserID uuid.UUID) ([]entity.AdminImpersonationLog, error) {
	ret := _m.Called(ctx, tx, adminUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveSessions")
	}

	var r0 []entity.AdminImpersonationLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) ([]entity.AdminImpersonationLog, error)); ok {
		return rf(ctx, tx, adminUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) []entity.AdminImpersonationLog); ok {
		r0 = rf(ctx, tx, adminUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AdminImpersonationLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, adminUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByAdminID provides a mock function with given fields: ctx, tx, adminUserID, offset, limit
func (_m *IAdminImpersonationLogRepository) FindByAdminID(ctx context.Context, tx *gorm.DB, adminUserID uuid.UUID, offset int, limit int) ([]entity.AdminImpersonationLog, int64, error) {
	ret := _m.Called(ctx, tx, adminUserID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByAdminID")
	}

	var r0 []entity.AdminImpersonationLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, int, int) ([]entity.AdminImpersonationLog, int64, error)); ok {
		return rf(ctx, tx, adminUserID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, int, int) []entity.AdminImpersonationLog); ok {
		r0 = rf(ctx, tx, adminUserID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AdminImpersonationLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID, int, int) int64); ok {
		r1 = rf(ctx, tx, adminUserID, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *gorm.DB, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, tx, adminUserID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByClientID provides a mock function with given fields: ctx, tx, clientID, offset, limit
func (_m *IAdminImpersonationLogRepository) FindByClientID(ctx context.Context, tx *gorm.DB, clientID uuid.UUID, offset int, limit int) ([]entity.AdminImpersonationLog, int64, error) {
	ret := _m.Called(ctx, tx, clientID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByClientID")
	}

	var r0 []entity.AdminImpersonationLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, int, int) ([]entity.AdminImpersonationLog, int64, error)); ok {
		return rf(ctx, tx, clientID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, int, int) []entity.AdminImpersonationLog); ok {
		r0 = rf(ctx, tx, clientID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AdminImpersonationLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID, int, int) int64); ok {
		r1 = rf(ctx, tx, clientID, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *gorm.DB, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, tx, clientID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewIAdminImpersonationLogRepository creates a new instance of IAdminImpersonationLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdminImpersonationLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdminImpersonationLogRepository {
	mock := &IAdminImpersonationLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
