// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// IAdminUserRepository is an autogenerated mock type for the IAdminUserRepository type
type IAdminUserRepository struct {
	mock.Mock
}

// CountById provides a mock function with given fields: ctx, tx, id
func (_m *IAdminUserRepository) CountById(ctx context.Context, tx *gorm.DB, id interface{}) (int64, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountById")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) (int64, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) int64); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, interface{}) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, tx, _a2
func (_m *IAdminUserRepository) Create(ctx context.Context, tx *gorm.DB, _a2 *entity.AdminUser) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.AdminUser) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tx, _a2
func (_m *IAdminUserRepository) Delete(ctx context.Context, tx *gorm.DB, _a2 *entity.AdminUser) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.AdminUser) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmailExists provides a mock function with given fields: ctx, tx, email
func (_m *IAdminUserRepository) EmailExists(ctx context.Context, tx *gorm.DB, email string) (bool, error) {
	ret := _m.Called(ctx, tx, email)

	if len(ret) == 0 {
		panic("no return value specified for EmailExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (bool, error)); ok {
		return rf(ctx, tx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) bool); ok {
		r0 = rf(ctx, tx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = rf(ctx, tx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, tx
func (_m *IAdminUserRepository) FindAll(ctx context.Context, tx *gorm.DB) ([]entity.AdminUser, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.AdminUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]entity.AdminUser, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []entity.AdminUser); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AdminUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllPaginated provides a mock function with given fields: ctx, tx, offset, limit
func (_m *IAdminUserRepository) FindAllPaginated(ctx context.Context, tx *gorm.DB, offset int, limit int) ([]entity.AdminUser, int64, error) {
	ret := _m.Called(ctx, tx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaginated")
	}

	var r0 []entity.AdminUser
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int, int) ([]entity.AdminUser, int64, error)); ok {
		return rf(ctx, tx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int, int) []entity.AdminUser); ok {
		r0 = rf(ctx, tx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AdminUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int, int) int64); ok {
		r1 = rf(ctx, tx, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *gorm.DB, int, int) error); ok {
		r2 = rf(ctx, tx, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindAllPaginatedWithRoles provides a mock function with given fields: ctx, tx, offset, limit
func (_m *IAdminUserRepository) FindAllPaginatedWithRoles(ctx context.Context, tx *gorm.DB, offset int, limit int) ([]entity.AdminUser, int64, error) {
	ret := _m.Called(ctx, tx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaginatedWithRoles")
	}

	var r0 []entity.AdminUser
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int, int) ([]entity.AdminUser, int64, error)); ok {
		return rf(ctx, tx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int, int) []entity.AdminUser); ok {
		r0 = rf(ctx, tx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AdminUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int, int) int64); ok {
		r1 = rf(ctx, tx, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *gorm.DB, int, int) error); ok {
		r2 = rf(ctx, tx, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByEmail provides a mock function with given fields: ctx, tx, email
func (_m *IAdminUserRepository) FindByEmail(ctx context.Context, tx *gorm.DB, email string) (*entity.AdminUser, error) {
	ret := _m.Called(ctx, tx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entity.AdminUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (*entity.AdminUser, error)); ok {
		return rf(ctx, tx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) *entity.AdminUser); ok {
		r0 = rf(ctx, tx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AdminUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = rf(ctx, tx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIDWithRoles provides a mock function with given fields: ctx, tx, id
func (_m *IAdminUserRepository) FindByIDWithRoles(ctx context.Context, tx *gorm.DB, id uuid.UUID) (*entity.AdminUser, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDWithRoles")
	}

	var r0 *entity.AdminUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.AdminUser, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.AdminUser); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AdminUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, tx, _a2, id
func (_m *IAdminUserRepository) FindById(ctx context.Context, tx *gorm.DB, _a2 *entity.AdminUser, id interface{}) error {
	ret := _m.Called(ctx, tx, _a2, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.AdminUser, interface{}) error); ok {
		r0 = rf(ctx, tx, _a2, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IncrementFailedLogin provides a mock function with given fields: ctx, tx, id
func (_m *IAdminUserRepository) IncrementFailedLogin(ctx context.Context, tx *gorm.DB, id uuid.UUID) error {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementFailedLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LockAccount provides a mock function with given fields: ctx, tx, id, until
func (_m *IAdminUserRepository) LockAccount(ctx context.Context, tx *gorm.DB, id uuid.UUID, until time.Time) error {
	ret := _m.Called(ctx, tx, id, until)

	if len(ret) == 0 {
		panic("no return value specified for LockAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, tx, id, until)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResetFailedLogin provides a mock function with given fields: ctx, tx, id
func (_m *IAdminUserRepository) ResetFailedLogin(ctx context.Context, tx *gorm.DB, id uuid.UUID) error {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for ResetFailedLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, tx, _a2
func (_m *IAdminUserRepository) Update(ctx context.Context, tx *gorm.DB, _a2 *entity.AdminUser) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.AdminUser) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update2FAStatus provides a mock function with given fields: ctx, tx, id, enabled
func (_m *IAdminUserRepository) Update2FAStatus(ctx context.Context, tx *gorm.DB, id uuid.UUID, enabled bool) error {
	ret := _m.Called(ctx, tx, id, enabled)

	if len(ret) == 0 {
		panic("no return value specified for Update2FAStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, tx, id, enabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLoginInfo provides a mock function with given fields: ctx, tx, id, ip, loginAt
func (_m *IAdminUserRepository) UpdateLoginInfo(ctx context.Context, tx *gorm.DB, id uuid.UUID, ip string, loginAt time.Time) error {
	ret := _m.Called(ctx, tx, id, ip, loginAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLoginInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, string, time.Time) error); ok {
		r0 = rf(ctx, tx, id, ip, loginAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAdminUserRepository creates a new instance of IAdminUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdminUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdminUserRepository {
	mock := &IAdminUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
