// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IAdminPermissionRepository is an autogenerated mock type for the IAdminPermissionRepository type
type IAdminPermissionRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: ctx, db
func (_m *IAdminPermissionRepository) FindAll(ctx context.Context, db *gorm.DB) ([]entity.AdminPermission, error) {
	ret := _m.Called(ctx, db)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.AdminPermission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]entity.AdminPermission, error)); ok {
		return rf(ctx, db)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []entity.AdminPermission); ok {
		r0 = rf(ctx, db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AdminPermission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, db)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByAdminUserID provides a mock function with given fields: ctx, db, adminID
func (_m *IAdminPermissionRepository) FindAllByAdminUserID(ctx context.Context, db *gorm.DB, adminID uuid.UUID) ([]entity.AdminPermission, error) {
	ret := _m.Called(ctx, db, adminID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByAdminUserID")
	}

	var r0 []entity.AdminPermission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) ([]entity.AdminPermission, error)); ok {
		return rf(ctx, db, adminID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) []entity.AdminPermission); ok {
		r0 = rf(ctx, db, adminID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AdminPermission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, db, adminID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, db, id
func (_m *IAdminPermissionRepository) FindByID(ctx context.Context, db *gorm.DB, id uuid.UUID) (*entity.AdminPermission, error) {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.AdminPermission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.AdminPermission, error)); ok {
		return rf(ctx, db, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.AdminPermission); ok {
		r0 = rf(ctx, db, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AdminPermission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, db, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: ctx, db, name
func (_m *IAdminPermissionRepository) FindByName(ctx context.Context, db *gorm.DB, name string) (*entity.AdminPermission, error) {
	ret := _m.Called(ctx, db, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *entity.AdminPermission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (*entity.AdminPermission, error)); ok {
		return rf(ctx, db, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) *entity.AdminPermission); ok {
		r0 = rf(ctx, db, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AdminPermission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = rf(ctx, db, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPermissionNamesByAdminUserID provides a mock function with given fields: ctx, db, adminID
func (_m *IAdminPermissionRepository) FindPermissionNamesByAdminUserID(ctx context.Context, db *gorm.DB, adminID uuid.UUID) ([]string, error) {
	ret := _m.Called(ctx, db, adminID)

	if len(ret) == 0 {
		panic("no return value specified for FindPermissionNamesByAdminUserID")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) ([]string, error)); ok {
		return rf(ctx, db, adminID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) []string); ok {
		r0 = rf(ctx, db, adminID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, db, adminID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAdminPermissionRepository creates a new instance of IAdminPermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdminPermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdminPermissionRepository {
	mock := &IAdminPermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
