// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IAdminRoleRepository is an autogenerated mock type for the IAdminRoleRepository type
type IAdminRoleRepository struct {
	mock.Mock
}

// AssignPermissions provides a mock function with given fields: ctx, db, roleID, permissionIDs
func (_m *IAdminRoleRepository) AssignPermissions(ctx context.Context, db *gorm.DB, roleID uuid.UUID, permissionIDs []uuid.UUID) error {
	ret := _m.Called(ctx, db, roleID, permissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for AssignPermissions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, []uuid.UUID) error); ok {
		r0 = rf(ctx, db, roleID, permissionIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AssignRoleToAdmin provides a mock function with given fields: ctx, db, adminID, roleID
func (_m *IAdminRoleRepository) AssignRoleToAdmin(ctx context.Context, db *gorm.DB, adminID uuid.UUID, roleID uuid.UUID) error {
	ret := _m.Called(ctx, db, adminID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for AssignRoleToAdmin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, db, adminID, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, db, role
func (_m *IAdminRoleRepository) Create(ctx context.Context, db *gorm.DB, role *entity.AdminRole) error {
	ret := _m.Called(ctx, db, role)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.AdminRole) error); ok {
		r0 = rf(ctx, db, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, db, id
func (_m *IAdminRoleRepository) Delete(ctx context.Context, db *gorm.DB, id uuid.UUID) error {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r0 = rf(ctx, db, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, db
func (_m *IAdminRoleRepository) FindAll(ctx context.Context, db *gorm.DB) ([]entity.AdminRole, error) {
	ret := _m.Called(ctx, db)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.AdminRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]entity.AdminRole, error)); ok {
		return rf(ctx, db)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []entity.AdminRole); ok {
		r0 = rf(ctx, db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AdminRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, db)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByAdminUserID provides a mock function with given fields: ctx, db, adminID
func (_m *IAdminRoleRepository) FindByAdminUserID(ctx context.Context, db *gorm.DB, adminID uuid.UUID) ([]entity.AdminRole, error) {
	ret := _m.Called(ctx, db, adminID)

	if len(ret) == 0 {
		panic("no return value specified for FindByAdminUserID")
	}

	var r0 []entity.AdminRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) ([]entity.AdminRole, error)); ok {
		return rf(ctx, db, adminID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) []entity.AdminRole); ok {
		r0 = rf(ctx, db, adminID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AdminRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, db, adminID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, db, id
func (_m *IAdminRoleRepository) FindByID(ctx context.Context, db *gorm.DB, id uuid.UUID) (*entity.AdminRole, error) {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.AdminRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.AdminRole, error)); ok {
		return rf(ctx, db, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.AdminRole); ok {
		r0 = rf(ctx, db, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AdminRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, db, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: ctx, db, name
func (_m *IAdminRoleRepository) FindByName(ctx context.Context, db *gorm.DB, name string) (*entity.AdminRole, error) {
	ret := _m.Called(ctx, db, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *entity.AdminRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (*entity.AdminRole, error)); ok {
		return rf(ctx, db, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) *entity.AdminRole); ok {
		r0 = rf(ctx, db, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AdminRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = rf(ctx, db, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokePermissions provides a mock function with given fields: ctx, db, roleID, permissionIDs
func (_m *IAdminRoleRepository) RevokePermissions(ctx context.Context, db *gorm.DB, roleID uuid.UUID, permissionIDs []uuid.UUID) error {
	ret := _m.Called(ctx, db, roleID, permissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for RevokePermissions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, []uuid.UUID) error); ok {
		r0 = rf(ctx, db, roleID, permissionIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeRoleFromAdmin provides a mock function with given fields: ctx, db, adminID, roleID
func (_m *IAdminRoleRepository) RevokeRoleFromAdmin(ctx context.Context, db *gorm.DB, adminID uuid.UUID, roleID uuid.UUID) error {
	ret := _m.Called(ctx, db, adminID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRoleFromAdmin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, db, adminID, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SyncAdminRoles provides a mock function with given fields: ctx, db, adminID, roleIDs
func (_m *IAdminRoleRepository) SyncAdminRoles(ctx context.Context, db *gorm.DB, adminID uuid.UUID, roleIDs []uuid.UUID) error {
	ret := _m.Called(ctx, db, adminID, roleIDs)

	if len(ret) == 0 {
		panic("no return value specified for SyncAdminRoles")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, []uuid.UUID) error); ok {
		r0 = rf(ctx, db, adminID, roleIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SyncPermissions provides a mock function with given fields: ctx, db, roleID, permissionIDs
func (_m *IAdminRoleRepository) SyncPermissions(ctx context.Context, db *gorm.DB, roleID uuid.UUID, permissionIDs []uuid.UUID) error {
	ret := _m.Called(ctx, db, roleID, permissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for SyncPermissions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, []uuid.UUID) error); ok {
		r0 = rf(ctx, db, roleID, permissionIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, db, role
func (_m *IAdminRoleRepository) Update(ctx context.Context, db *gorm.DB, role *entity.AdminRole) error {
	ret := _m.Called(ctx, db, role)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.AdminRole) error); ok {
		r0 = rf(ctx, db, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAdminRoleRepository creates a new instance of IAdminRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdminRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdminRoleRepository {
	mock := &IAdminRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
