// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IAuditLogRepository is an autogenerated mock type for the IAuditLogRepository type
type IAuditLogRepository struct {
	mock.Mock
}

// CountById provides a mock function with given fields: ctx, tx, id
func (_m *IAuditLogRepository) CountById(ctx context.Context, tx *gorm.DB, id interface{}) (int64, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountById")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) (int64, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) int64); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, interface{}) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, tx, _a2
func (_m *IAuditLogRepository) Create(ctx context.Context, tx *gorm.DB, _a2 *entity.AuditLog) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.AuditLog) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tx, _a2
func (_m *IAuditLogRepository) Delete(ctx context.Context, tx *gorm.DB, _a2 *entity.AuditLog) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.AuditLog) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, tx
func (_m *IAuditLogRepository) FindAll(ctx context.Context, tx *gorm.DB) ([]entity.AuditLog, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]entity.AuditLog, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []entity.AuditLog); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByClient provides a mock function with given fields: ctx, db, clientID, limit, offset
func (_m *IAuditLogRepository) FindAllByClient(ctx context.Context, db *gorm.DB, clientID uuid.UUID, limit int, offset int) ([]entity.AuditLog, int64, error) {
	ret := _m.Called(ctx, db, clientID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByClient")
	}

	var r0 []entity.AuditLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, int, int) ([]entity.AuditLog, int64, error)); ok {
		return rf(ctx, db, clientID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, int, int) []entity.AuditLog); ok {
		r0 = rf(ctx, db, clientID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID, int, int) int64); ok {
		r1 = rf(ctx, db, clientID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *gorm.DB, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, db, clientID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindAllPlatform provides a mock function with given fields: ctx, db, limit, offset
func (_m *IAuditLogRepository) FindAllPlatform(ctx context.Context, db *gorm.DB, limit int, offset int) ([]entity.AuditLog, int64, error) {
	ret := _m.Called(ctx, db, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPlatform")
	}

	var r0 []entity.AuditLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int, int) ([]entity.AuditLog, int64, error)); ok {
		return rf(ctx, db, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int, int) []entity.AuditLog); ok {
		r0 = rf(ctx, db, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int, int) int64); ok {
		r1 = rf(ctx, db, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *gorm.DB, int, int) error); ok {
		r2 = rf(ctx, db, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByEntity provides a mock function with given fields: ctx, tx, entityType, entityID
func (_m *IAuditLogRepository) FindByEntity(ctx context.Context, tx *gorm.DB, entityType string, entityID uuid.UUID) ([]entity.AuditLog, error) {
	ret := _m.Called(ctx, tx, entityType, entityID)

	if len(ret) == 0 {
		panic("no return value specified for FindByEntity")
	}

	var r0 []entity.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string, uuid.UUID) ([]entity.AuditLog, error)); ok {
		return rf(ctx, tx, entityType, entityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string, uuid.UUID) []entity.AuditLog); ok {
		r0 = rf(ctx, tx, entityType, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, tx, _a2, id
func (_m *IAuditLogRepository) FindById(ctx context.Context, tx *gorm.DB, _a2 *entity.AuditLog, id interface{}) error {
	ret := _m.Called(ctx, tx, _a2, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.AuditLog, interface{}) error); ok {
		r0 = rf(ctx, tx, _a2, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, tx, _a2
func (_m *IAuditLogRepository) Update(ctx context.Context, tx *gorm.DB, _a2 *entity.AuditLog) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.AuditLog) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAuditLogRepository creates a new instance of IAuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuditLogRepository {
	mock := &IAuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
