// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"

	uuid "github.com/google/uuid"
)

// IClientRepository is an autogenerated mock type for the IClientRepository type
type IClientRepository struct {
	mock.Mock
}

// Activate provides a mock function with given fields: ctx, tx, client
func (_m *IClientRepository) Activate(ctx context.Context, tx *gorm.DB, client *entity.Client) error {
	ret := _m.Called(ctx, tx, client)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Client) error); ok {
		r0 = rf(ctx, tx, client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountById provides a mock function with given fields: ctx, tx, id
func (_m *IClientRepository) CountById(ctx context.Context, tx *gorm.DB, id interface{}) (int64, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountById")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) (int64, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) int64); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, interface{}) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, tx, _a2
func (_m *IClientRepository) Create(ctx context.Context, tx *gorm.DB, _a2 *entity.Client) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Client) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Deactivate provides a mock function with given fields: ctx, tx, client
func (_m *IClientRepository) Deactivate(ctx context.Context, tx *gorm.DB, client *entity.Client) error {
	ret := _m.Called(ctx, tx, client)

	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Client) error); ok {
		r0 = rf(ctx, tx, client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tx, _a2
func (_m *IClientRepository) Delete(ctx context.Context, tx *gorm.DB, _a2 *entity.Client) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Client) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, tx
func (_m *IClientRepository) FindAll(ctx context.Context, tx *gorm.DB) ([]entity.Client, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]entity.Client, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []entity.Client); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllPaginated provides a mock function with given fields: ctx, tx, req
func (_m *IClientRepository) FindAllPaginated(ctx context.Context, tx *gorm.DB, req *model.AdminListAllClientsRequest) ([]entity.Client, int64, error) {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaginated")
	}

	var r0 []entity.Client
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *model.AdminListAllClientsRequest) ([]entity.Client, int64, error)); ok {
		return rf(ctx, tx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *model.AdminListAllClientsRequest) []entity.Client); ok {
		r0 = rf(ctx, tx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, *model.AdminListAllClientsRequest) int64); ok {
		r1 = rf(ctx, tx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *gorm.DB, *model.AdminListAllClientsRequest) error); ok {
		r2 = rf(ctx, tx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByEmail provides a mock function with given fields: ctx, tx, email
func (_m *IClientRepository) FindByEmail(ctx context.Context, tx *gorm.DB, email string) (*entity.Client, error) {
	ret := _m.Called(ctx, tx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entity.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (*entity.Client, error)); ok {
		return rf(ctx, tx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) *entity.Client); ok {
		r0 = rf(ctx, tx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = rf(ctx, tx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, tx, id
func (_m *IClientRepository) FindByID(ctx context.Context, tx *gorm.DB, id uuid.UUID) (*entity.Client, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.Client, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.Client); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIDWithOwner provides a mock function with given fields: ctx, tx, id
func (_m *IClientRepository) FindByIDWithOwner(ctx context.Context, tx *gorm.DB, id uuid.UUID) (*entity.Client, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDWithOwner")
	}

	var r0 *entity.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.Client, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.Client); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, tx, _a2, id
func (_m *IClientRepository) FindById(ctx context.Context, tx *gorm.DB, _a2 *entity.Client, id interface{}) error {
	ret := _m.Called(ctx, tx, _a2, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Client, interface{}) error); ok {
		r0 = rf(ctx, tx, _a2, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindBySlug provides a mock function with given fields: ctx, tx, slug
func (_m *IClientRepository) FindBySlug(ctx context.Context, tx *gorm.DB, slug string) (*entity.Client, error) {
	ret := _m.Called(ctx, tx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindBySlug")
	}

	var r0 *entity.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (*entity.Client, error)); ok {
		return rf(ctx, tx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) *entity.Client); ok {
		r0 = rf(ctx, tx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = rf(ctx, tx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SoftDelete provides a mock function with given fields: ctx, tx, client
func (_m *IClientRepository) SoftDelete(ctx context.Context, tx *gorm.DB, client *entity.Client) error {
	ret := _m.Called(ctx, tx, client)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Client) error); ok {
		r0 = rf(ctx, tx, client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, tx, _a2
func (_m *IClientRepository) Update(ctx context.Context, tx *gorm.DB, _a2 *entity.Client) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Client) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIClientRepository creates a new instance of IClientRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIClientRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IClientRepository {
	mock := &IClientRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
