// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"

	uuid "github.com/google/uuid"
)

// IClientUserRepository is an autogenerated mock type for the IClientUserRepository type
type IClientUserRepository struct {
	mock.Mock
}

// CountActiveByUserID provides a mock function with given fields: ctx, tx, userID
func (_m *IClientUserRepository) CountActiveByUserID(ctx context.Context, tx *gorm.DB, userID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveByUserID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (int64, error)); ok {
		return rf(ctx, tx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) int64); ok {
		r0 = rf(ctx, tx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, tx, clientUser
func (_m *IClientUserRepository) Create(ctx context.Context, tx *gorm.DB, clientUser *entity.ClientUser) error {
	ret := _m.Called(ctx, tx, clientUser)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.ClientUser) error); ok {
		r0 = rf(ctx, tx, clientUser)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllByClientIDPaginated provides a mock function with given fields: ctx, tx, req
func (_m *IClientUserRepository) FindAllByClientIDPaginated(ctx context.Context, tx *gorm.DB, req *model.AdminTenantUserListRequest) ([]entity.ClientUser, int64, error) {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByClientIDPaginated")
	}

	var r0 []entity.ClientUser
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *model.AdminTenantUserListRequest) ([]entity.ClientUser, int64, error)); ok {
		return rf(ctx, tx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *model.AdminTenantUserListRequest) []entity.ClientUser); ok {
		r0 = rf(ctx, tx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ClientUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, *model.AdminTenantUserListRequest) int64); ok {
		r1 = rf(ctx, tx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *gorm.DB, *model.AdminTenantUserListRequest) error); ok {
		r2 = rf(ctx, tx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByClientAndUserID provides a mock function with given fields: ctx, tx, clientID, userID
func (_m *IClientUserRepository) FindByClientAndUserID(ctx context.Context, tx *gorm.DB, clientID uuid.UUID, userID uuid.UUID) (*entity.ClientUser, error) {
	ret := _m.Called(ctx, tx, clientID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByClientAndUserID")
	}

	var r0 *entity.ClientUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID) (*entity.ClientUser, error)); ok {
		return rf(ctx, tx, clientID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID) *entity.ClientUser); ok {
		r0 = rf(ctx, tx, clientID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ClientUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, clientID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SoftDelete provides a mock function with given fields: ctx, tx, id
func (_m *IClientUserRepository) SoftDelete(ctx context.Context, tx *gorm.DB, id uuid.UUID) error {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SoftDeleteByClientID provides a mock function with given fields: ctx, tx, clientID
func (_m *IClientUserRepository) SoftDeleteByClientID(ctx context.Context, tx *gorm.DB, clientID uuid.UUID) error {
	ret := _m.Called(ctx, tx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteByClientID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r0 = rf(ctx, tx, clientID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, tx, clientUser
func (_m *IClientUserRepository) Update(ctx context.Context, tx *gorm.DB, clientUser *entity.ClientUser) error {
	ret := _m.Called(ctx, tx, clientUser)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.ClientUser) error); ok {
		r0 = rf(ctx, tx, clientUser)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIClientUserRepository creates a new instance of IClientUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIClientUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IClientUserRepository {
	mock := &IClientUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
