// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// IClientBillingRepository is an autogenerated mock type for the IClientBillingRepository type
type IClientBillingRepository struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: ctx, tx, id
func (_m *IClientBillingRepository) Cancel(ctx context.Context, tx *gorm.DB, id uuid.UUID) error {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountActiveByPlanID provides a mock function with given fields: ctx, tx, planID
func (_m *IClientBillingRepository) CountActiveByPlanID(ctx context.Context, tx *gorm.DB, planID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, tx, planID)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveByPlanID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (int64, error)); ok {
		return rf(ctx, tx, planID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) int64); ok {
		r0 = rf(ctx, tx, planID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, planID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountById provides a mock function with given fields: ctx, tx, id
func (_m *IClientBillingRepository) CountById(ctx context.Context, tx *gorm.DB, id interface{}) (int64, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountById")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) (int64, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) int64); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, interface{}) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, db, billing
func (_m *IClientBillingRepository) Create(ctx context.Context, db *gorm.DB, billing *entity.ClientBilling) error {
	ret := _m.Called(ctx, db, billing)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.ClientBilling) error); ok {
		r0 = rf(ctx, db, billing)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tx, _a2
func (_m *IClientBillingRepository) Delete(ctx context.Context, tx *gorm.DB, _a2 *entity.ClientBilling) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.ClientBilling) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindActiveByClientID provides a mock function with given fields: ctx, tx, clientID
func (_m *IClientBillingRepository) FindActiveByClientID(ctx context.Context, tx *gorm.DB, clientID uuid.UUID) (*entity.ClientBilling, error) {
	ret := _m.Called(ctx, tx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByClientID")
	}

	var r0 *entity.ClientBilling
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.ClientBilling, error)); ok {
		return rf(ctx, tx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.ClientBilling); ok {
		r0 = rf(ctx, tx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ClientBilling)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindActiveOrPendingByClientID provides a mock function with given fields: ctx, tx, clientID
func (_m *IClientBillingRepository) FindActiveOrPendingByClientID(ctx context.Context, tx *gorm.DB, clientID uuid.UUID) (*entity.ClientBilling, error) {
	ret := _m.Called(ctx, tx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveOrPendingByClientID")
	}

	var r0 *entity.ClientBilling
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.ClientBilling, error)); ok {
		return rf(ctx, tx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.ClientBilling); ok {
		r0 = rf(ctx, tx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ClientBilling)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, tx
func (_m *IClientBillingRepository) FindAll(ctx context.Context, tx *gorm.DB) ([]entity.ClientBilling, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.ClientBilling
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]entity.ClientBilling, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []entity.ClientBilling); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ClientBilling)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByClientID provides a mock function with given fields: ctx, tx, clientID
func (_m *IClientBillingRepository) FindAllByClientID(ctx context.Context, tx *gorm.DB, clientID uuid.UUID) ([]entity.ClientBilling, error) {
	ret := _m.Called(ctx, tx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByClientID")
	}

	var r0 []entity.ClientBilling
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) ([]entity.ClientBilling, error)); ok {
		return rf(ctx, tx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) []entity.ClientBilling); ok {
		r0 = rf(ctx, tx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ClientBilling)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllPaginated provides a mock function with given fields: ctx, db, clientID, status, offset, limit
func (_m *IClientBillingRepository) FindAllPaginated(ctx context.Context, db *gorm.DB, clientID *uuid.UUID, status string, offset int, limit int) ([]entity.ClientBilling, int64, error) {
	ret := _m.Called(ctx, db, clientID, status, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaginated")
	}

	var r0 []entity.ClientBilling
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *uuid.UUID, string, int, int) ([]entity.ClientBilling, int64, error)); ok {
		return rf(ctx, db, clientID, status, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *uuid.UUID, string, int, int) []entity.ClientBilling); ok {
		r0 = rf(ctx, db, clientID, status, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ClientBilling)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, *uuid.UUID, string, int, int) int64); ok {
		r1 = rf(ctx, db, clientID, status, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *gorm.DB, *uuid.UUID, string, int, int) error); ok {
		r2 = rf(ctx, db, clientID, status, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByExternalID provides a mock function with given fields: ctx, db, externalID
func (_m *IClientBillingRepository) FindByExternalID(ctx context.Context, db *gorm.DB, externalID string) (*entity.ClientBilling, error) {
	ret := _m.Called(ctx, db, externalID)

	if len(ret) == 0 {
		panic("no return value specified for FindByExternalID")
	}

	var r0 *entity.ClientBilling
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (*entity.ClientBilling, error)); ok {
		return rf(ctx, db, externalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) *entity.ClientBilling); ok {
		r0 = rf(ctx, db, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ClientBilling)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = rf(ctx, db, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, db, id
func (_m *IClientBillingRepository) FindByID(ctx context.Context, db *gorm.DB, id uuid.UUID) (*entity.ClientBilling, error) {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.ClientBilling
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.ClientBilling, error)); ok {
		return rf(ctx, db, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.ClientBilling); ok {
		r0 = rf(ctx, db, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ClientBilling)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, db, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, tx, _a2, id
func (_m *IClientBillingRepository) FindById(ctx context.Context, tx *gorm.DB, _a2 *entity.ClientBilling, id interface{}) error {
	ret := _m.Called(ctx, tx, _a2, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.ClientBilling, interface{}) error); ok {
		r0 = rf(ctx, tx, _a2, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindExpiredActives provides a mock function with given fields: ctx, db, before
func (_m *IClientBillingRepository) FindExpiredActives(ctx context.Context, db *gorm.DB, before time.Time) ([]entity.ClientBilling, error) {
	ret := _m.Called(ctx, db, before)

	if len(ret) == 0 {
		panic("no return value specified for FindExpiredActives")
	}

	var r0 []entity.ClientBilling
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, time.Time) ([]entity.ClientBilling, error)); ok {
		return rf(ctx, db, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, time.Time) []entity.ClientBilling); ok {
		r0 = rf(ctx, db, before)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ClientBilling)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, time.Time) error); ok {
		r1 = rf(ctx, db, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindExpiring provides a mock function with given fields: ctx, tx, before
func (_m *IClientBillingRepository) FindExpiring(ctx context.Context, tx *gorm.DB, before time.Time) ([]entity.ClientBilling, error) {
	ret := _m.Called(ctx, tx, before)

	if len(ret) == 0 {
		panic("no return value specified for FindExpiring")
	}

	var r0 []entity.ClientBilling
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, time.Time) ([]entity.ClientBilling, error)); ok {
		return rf(ctx, tx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, time.Time) []entity.ClientBilling); ok {
		r0 = rf(ctx, tx, before)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ClientBilling)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, time.Time) error); ok {
		r1 = rf(ctx, tx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPastDue provides a mock function with given fields: ctx, tx
func (_m *IClientBillingRepository) FindPastDue(ctx context.Context, tx *gorm.DB) ([]entity.ClientBilling, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for FindPastDue")
	}

	var r0 []entity.ClientBilling
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]entity.ClientBilling, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []entity.ClientBilling); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ClientBilling)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, db, billing
func (_m *IClientBillingRepository) Update(ctx context.Context, db *gorm.DB, billing *entity.ClientBilling) error {
	ret := _m.Called(ctx, db, billing)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.ClientBilling) error); ok {
		r0 = rf(ctx, db, billing)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIClientBillingRepository creates a new instance of IClientBillingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIClientBillingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IClientBillingRepository {
	mock := &IClientBillingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
