// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	decimal "github.com/shopspring/decimal"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IMemberDiscountRepository is an autogenerated mock type for the IMemberDiscountRepository type
type IMemberDiscountRepository struct {
	mock.Mock
}

// CountUsageByUser provides a mock function with given fields: ctx, db, discountID, telegramUserID
func (_m *IMemberDiscountRepository) CountUsageByUser(ctx context.Context, db *gorm.DB, discountID uuid.UUID, telegramUserID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, db, discountID, telegramUserID)

	if len(ret) == 0 {
		panic("no return value specified for CountUsageByUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID) (int64, error)); ok {
		return rf(ctx, db, discountID, telegramUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID) int64); ok {
		r0 = rf(ctx, db, discountID, telegramUserID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, db, discountID, telegramUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, db, d
func (_m *IMemberDiscountRepository) Create(ctx context.Context, db *gorm.DB, d *entity.MemberDiscount) error {
	ret := _m.Called(ctx, db, d)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.MemberDiscount) error); ok {
		r0 = rf(ctx, db, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUsage provides a mock function with given fields: ctx, db, usage
func (_m *IMemberDiscountRepository) CreateUsage(ctx context.Context, db *gorm.DB, usage *entity.MemberDiscountUsage) error {
	ret := _m.Called(ctx, db, usage)

	if len(ret) == 0 {
		panic("no return value specified for CreateUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.MemberDiscountUsage) error); ok {
		r0 = rf(ctx, db, usage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecrementUsage provides a mock function with given fields: ctx, db, id
func (_m *IMemberDiscountRepository) DecrementUsage(ctx context.Context, db *gorm.DB, id uuid.UUID) error {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for DecrementUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r0 = rf(ctx, db, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUsageByOrderID provides a mock function with given fields: ctx, db, orderID
func (_m *IMemberDiscountRepository) DeleteUsageByOrderID(ctx context.Context, db *gorm.DB, orderID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, db, orderID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUsageByOrderID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (int64, error)); ok {
		return rf(ctx, db, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) int64); ok {
		r0 = rf(ctx, db, orderID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, db, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByClient provides a mock function with given fields: ctx, db, clientID, onlyActive
func (_m *IMemberDiscountRepository) FindAllByClient(ctx context.Context, db *gorm.DB, clientID uuid.UUID, onlyActive bool) ([]entity.MemberDiscount, error) {
	ret := _m.Called(ctx, db, clientID, onlyActive)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByClient")
	}

	var r0 []entity.MemberDiscount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, bool) ([]entity.MemberDiscount, error)); ok {
		return rf(ctx, db, clientID, onlyActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, bool) []entity.MemberDiscount); ok {
		r0 = rf(ctx, db, clientID, onlyActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.MemberDiscount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, db, clientID, onlyActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAutoApplicable provides a mock function with given fields: ctx, db, clientID, packageID, amount
func (_m *IMemberDiscountRepository) FindAutoApplicable(ctx context.Context, db *gorm.DB, clientID uuid.UUID, packageID uuid.UUID, amount decimal.Decimal) (*entity.MemberDiscount, error) {
	ret := _m.Called(ctx, db, clientID, packageID, amount)

	if len(ret) == 0 {
		panic("no return value specified for FindAutoApplicable")
	}

	var r0 *entity.MemberDiscount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID, decimal.Decimal) (*entity.MemberDiscount, error)); ok {
		return rf(ctx, db, clientID, packageID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID, decimal.Decimal) *entity.MemberDiscount); ok {
		r0 = rf(ctx, db, clientID, packageID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.MemberDiscount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID, decimal.Decimal) error); ok {
		r1 = rf(ctx, db, clientID, packageID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByCode provides a mock function with given fields: ctx, db, clientID, code
func (_m *IMemberDiscountRepository) FindByCode(ctx context.Context, db *gorm.DB, clientID uuid.UUID, code string) (*entity.MemberDiscount, error) {
	ret := _m.Called(ctx, db, clientID, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *entity.MemberDiscount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, string) (*entity.MemberDiscount, error)); ok {
		return rf(ctx, db, clientID, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, string) *entity.MemberDiscount); ok {
		r0 = rf(ctx, db, clientID, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.MemberDiscount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID, string) error); ok {
		r1 = rf(ctx, db, clientID, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, db, id
func (_m *IMemberDiscountRepository) FindByID(ctx context.Context, db *gorm.DB, id uuid.UUID) (*entity.MemberDiscount, error) {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.MemberDiscount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.MemberDiscount, error)); ok {
		return rf(ctx, db, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.MemberDiscount); ok {
		r0 = rf(ctx, db, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.MemberDiscount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, db, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementUsage provides a mock function with given fields: ctx, db, id
func (_m *IMemberDiscountRepository) IncrementUsage(ctx context.Context, db *gorm.DB, id uuid.UUID) error {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r0 = rf(ctx, db, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SoftDelete provides a mock function with given fields: ctx, db, id
func (_m *IMemberDiscountRepository) SoftDelete(ctx context.Context, db *gorm.DB, id uuid.UUID) error {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r0 = rf(ctx, db, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, db, d
func (_m *IMemberDiscountRepository) Update(ctx context.Context, db *gorm.DB, d *entity.MemberDiscount) error {
	ret := _m.Called(ctx, db, d)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.MemberDiscount) error); ok {
		r0 = rf(ctx, db, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIMemberDiscountRepository creates a new instance of IMemberDiscountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMemberDiscountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMemberDiscountRepository {
	mock := &IMemberDiscountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
