// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IOrderRepository is an autogenerated mock type for the IOrderRepository type
type IOrderRepository struct {
	mock.Mock
}

// CountById provides a mock function with given fields: ctx, tx, id
func (_m *IOrderRepository) CountById(ctx context.Context, tx *gorm.DB, id interface{}) (int64, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountById")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) (int64, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) int64); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, interface{}) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, tx, order
func (_m *IOrderRepository) Create(ctx context.Context, tx *gorm.DB, order *entity.Order) error {
	ret := _m.Called(ctx, tx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Order) error); ok {
		r0 = rf(ctx, tx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tx, _a2
func (_m *IOrderRepository) Delete(ctx context.Context, tx *gorm.DB, _a2 *entity.Order) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Order) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, tx
func (_m *IOrderRepository) FindAll(ctx context.Context, tx *gorm.DB) ([]entity.Order, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]entity.Order, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []entity.Order); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByExternalID provides a mock function with given fields: ctx, tx, externalID
func (_m *IOrderRepository) FindByExternalID(ctx context.Context, tx *gorm.DB, externalID string) (*entity.Order, error) {
	ret := _m.Called(ctx, tx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for FindByExternalID")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (*entity.Order, error)); ok {
		return rf(ctx, tx, externalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) *entity.Order); ok {
		r0 = rf(ctx, tx, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = rf(ctx, tx, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, tx, id
func (_m *IOrderRepository) FindByID(ctx context.Context, tx *gorm.DB, id uuid.UUID) (*entity.Order, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.Order, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.Order); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBySubscriptionID provides a mock function with given fields: ctx, tx, subscriptionID
func (_m *IOrderRepository) FindBySubscriptionID(ctx context.Context, tx *gorm.DB, subscriptionID uuid.UUID) (*entity.Order, error) {
	ret := _m.Called(ctx, tx, subscriptionID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySubscriptionID")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.Order, error)); ok {
		return rf(ctx, tx, subscriptionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.Order); ok {
		r0 = rf(ctx, tx, subscriptionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, subscriptionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindRecentByTelegramUserID provides a mock function with given fields: ctx, tx, telegramUserID, clientID, limit
func (_m *IOrderRepository) FindRecentByTelegramUserID(ctx context.Context, tx *gorm.DB, telegramUserID int64, clientID uuid.UUID, limit int) ([]entity.Order, error) {
	ret := _m.Called(ctx, tx, telegramUserID, clientID, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindRecentByTelegramUserID")
	}

	var r0 []entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, uuid.UUID, int) ([]entity.Order, error)); ok {
		return rf(ctx, tx, telegramUserID, clientID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, uuid.UUID, int) []entity.Order); ok {
		r0 = rf(ctx, tx, telegramUserID, clientID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int64, uuid.UUID, int) error); ok {
		r1 = rf(ctx, tx, telegramUserID, clientID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, tx, _a2, id
func (_m *IOrderRepository) FindById(ctx context.Context, tx *gorm.DB, _a2 *entity.Order, id interface{}) error {
	ret := _m.Called(ctx, tx, _a2, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Order, interface{}) error); ok {
		r0 = rf(ctx, tx, _a2, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindExpiredPendingOrders provides a mock function with given fields: ctx, tx, limit
func (_m *IOrderRepository) FindExpiredPendingOrders(ctx context.Context, tx *gorm.DB, limit int) ([]entity.Order, error) {
	ret := _m.Called(ctx, tx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindExpiredPendingOrders")
	}

	var r0 []entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int) ([]entity.Order, error)); ok {
		return rf(ctx, tx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int) []entity.Order); ok {
		r0 = rf(ctx, tx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int) error); ok {
		r1 = rf(ctx, tx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPendingOrderByUserAndPackage provides a mock function with given fields: ctx, tx, userID, packageID
func (_m *IOrderRepository) FindPendingOrderByUserAndPackage(ctx context.Context, tx *gorm.DB, userID uuid.UUID, packageID uuid.UUID) (*entity.Order, error) {
	ret := _m.Called(ctx, tx, userID, packageID)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingOrderByUserAndPackage")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID) (*entity.Order, error)); ok {
		return rf(ctx, tx, userID, packageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID) *entity.Order); ok {
		r0 = rf(ctx, tx, userID, packageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, userID, packageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, tx, order
func (_m *IOrderRepository) Update(ctx context.Context, tx *gorm.DB, order *entity.Order) error {
	ret := _m.Called(ctx, tx, order)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Order) error); ok {
		r0 = rf(ctx, tx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindTransactionsByClientID provides a mock function with given fields: ctx, tx, clientID, filter
func (_m *IOrderRepository) FindTransactionsByClientID(ctx context.Context, tx *gorm.DB, clientID uuid.UUID, filter model.TransactionFilterRequest) ([]entity.Order, error) {
	ret := _m.Called(ctx, tx, clientID, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindTransactionsByClientID")
	}

	var r0 []entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, model.TransactionFilterRequest) ([]entity.Order, error)); ok {
		return rf(ctx, tx, clientID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, model.TransactionFilterRequest) []entity.Order); ok {
		r0 = rf(ctx, tx, clientID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID, model.TransactionFilterRequest) error); ok {
		r1 = rf(ctx, tx, clientID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountTransactionsByClientID provides a mock function with given fields: ctx, tx, clientID, filter
func (_m *IOrderRepository) CountTransactionsByClientID(ctx context.Context, tx *gorm.DB, clientID uuid.UUID, filter model.TransactionFilterRequest) (int64, error) {
	ret := _m.Called(ctx, tx, clientID, filter)

	if len(ret) == 0 {
		panic("no return value specified for CountTransactionsByClientID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, model.TransactionFilterRequest) (int64, error)); ok {
		return rf(ctx, tx, clientID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, model.TransactionFilterRequest) int64); ok {
		r0 = rf(ctx, tx, clientID, filter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID, model.TransactionFilterRequest) error); ok {
		r1 = rf(ctx, tx, clientID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIOrderRepository creates a new instance of IOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOrderRepository {
	mock := &IOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
