// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// IOutboxRepository is an autogenerated mock type for the IOutboxRepository type
type IOutboxRepository struct {
	mock.Mock
}

// CountById provides a mock function with given fields: ctx, tx, id
func (_m *IOutboxRepository) CountById(ctx context.Context, tx *gorm.DB, id interface{}) (int64, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountById")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) (int64, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) int64); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, interface{}) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, db, outbox
func (_m *IOutboxRepository) Create(ctx context.Context, db *gorm.DB, outbox *entity.Outbox) error {
	ret := _m.Called(ctx, db, outbox)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Outbox) error); ok {
		r0 = rf(ctx, db, outbox)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tx, _a2
func (_m *IOutboxRepository) Delete(ctx context.Context, tx *gorm.DB, _a2 *entity.Outbox) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Outbox) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, tx
func (_m *IOutboxRepository) FindAll(ctx context.Context, tx *gorm.DB) ([]entity.Outbox, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.Outbox
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]entity.Outbox, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []entity.Outbox); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Outbox)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, tx, _a2, id
func (_m *IOutboxRepository) FindById(ctx context.Context, tx *gorm.DB, _a2 *entity.Outbox, id interface{}) error {
	ret := _m.Called(ctx, tx, _a2, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Outbox, interface{}) error); ok {
		r0 = rf(ctx, tx, _a2, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindPending provides a mock function with given fields: ctx, db, limit
func (_m *IOutboxRepository) FindPending(ctx context.Context, db *gorm.DB, limit int) ([]entity.Outbox, error) {
	ret := _m.Called(ctx, db, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindPending")
	}

	var r0 []entity.Outbox
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int) ([]entity.Outbox, error)); ok {
		return rf(ctx, db, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int) []entity.Outbox); ok {
		r0 = rf(ctx, db, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Outbox)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int) error); ok {
		r1 = rf(ctx, db, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, db, outbox
func (_m *IOutboxRepository) Update(ctx context.Context, db *gorm.DB, outbox *entity.Outbox) error {
	ret := _m.Called(ctx, db, outbox)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Outbox) error); ok {
		r0 = rf(ctx, db, outbox)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIOutboxRepository creates a new instance of IOutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOutboxRepository {
	mock := &IOutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
