// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IPackageRepository is an autogenerated mock type for the IPackageRepository type
type IPackageRepository struct {
	mock.Mock
}

// AssociateGroups provides a mock function with given fields: ctx, tx, pkg, groups
func (_m *IPackageRepository) AssociateGroups(ctx context.Context, tx *gorm.DB, pkg *entity.Package, groups []entity.Group) error {
	ret := _m.Called(ctx, tx, pkg, groups)

	if len(ret) == 0 {
		panic("no return value specified for AssociateGroups")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Package, []entity.Group) error); ok {
		r0 = rf(ctx, tx, pkg, groups)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountById provides a mock function with given fields: ctx, tx, id
func (_m *IPackageRepository) CountById(ctx context.Context, tx *gorm.DB, id interface{}) (int64, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountById")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) (int64, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) int64); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, interface{}) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, tx, _a2
func (_m *IPackageRepository) Create(ctx context.Context, tx *gorm.DB, _a2 *entity.Package) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Package) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tx, pkg
func (_m *IPackageRepository) Delete(ctx context.Context, tx *gorm.DB, pkg *entity.Package) error {
	ret := _m.Called(ctx, tx, pkg)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Package) error); ok {
		r0 = rf(ctx, tx, pkg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, tx
func (_m *IPackageRepository) FindAll(ctx context.Context, tx *gorm.DB) ([]entity.Package, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]entity.Package, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []entity.Package); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByClientID provides a mock function with given fields: ctx, tx, clientID
func (_m *IPackageRepository) FindByClientID(ctx context.Context, tx *gorm.DB, clientID uuid.UUID) ([]entity.Package, error) {
	ret := _m.Called(ctx, tx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for FindByClientID")
	}

	var r0 []entity.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) ([]entity.Package, error)); ok {
		return rf(ctx, tx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) []entity.Package); ok {
		r0 = rf(ctx, tx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByGroupID provides a mock function with given fields: ctx, tx, groupID
func (_m *IPackageRepository) FindByGroupID(ctx context.Context, tx *gorm.DB, groupID uuid.UUID) ([]entity.Package, error) {
	ret := _m.Called(ctx, tx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for FindByGroupID")
	}

	var r0 []entity.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) ([]entity.Package, error)); ok {
		return rf(ctx, tx, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) []entity.Package); ok {
		r0 = rf(ctx, tx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, tx, id
func (_m *IPackageRepository) FindByID(ctx context.Context, tx *gorm.DB, id uuid.UUID) (*entity.Package, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.Package, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.Package); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, tx, _a2, id
func (_m *IPackageRepository) FindById(ctx context.Context, tx *gorm.DB, _a2 *entity.Package, id interface{}) error {
	ret := _m.Called(ctx, tx, _a2, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Package, interface{}) error); ok {
		r0 = rf(ctx, tx, _a2, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, tx, _a2
func (_m *IPackageRepository) Update(ctx context.Context, tx *gorm.DB, _a2 *entity.Package) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Package) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIPackageRepository creates a new instance of IPackageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPackageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPackageRepository {
	mock := &IPackageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
