// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	decimal "github.com/shopspring/decimal"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IPlatformDiscountRepository is an autogenerated mock type for the IPlatformDiscountRepository type
type IPlatformDiscountRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, db, d
func (_m *IPlatformDiscountRepository) Create(ctx context.Context, db *gorm.DB, d *entity.PlatformDiscount) error {
	ret := _m.Called(ctx, db, d)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.PlatformDiscount) error); ok {
		r0 = rf(ctx, db, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, db, onlyActive
func (_m *IPlatformDiscountRepository) FindAll(ctx context.Context, db *gorm.DB, onlyActive bool) ([]entity.PlatformDiscount, error) {
	ret := _m.Called(ctx, db, onlyActive)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.PlatformDiscount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, bool) ([]entity.PlatformDiscount, error)); ok {
		return rf(ctx, db, onlyActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, bool) []entity.PlatformDiscount); ok {
		r0 = rf(ctx, db, onlyActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PlatformDiscount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, bool) error); ok {
		r1 = rf(ctx, db, onlyActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAutoApplicable provides a mock function with given fields: ctx, db, clientID, planID, amount
func (_m *IPlatformDiscountRepository) FindAutoApplicable(ctx context.Context, db *gorm.DB, clientID uuid.UUID, planID uuid.UUID, amount decimal.Decimal) (*entity.PlatformDiscount, error) {
	ret := _m.Called(ctx, db, clientID, planID, amount)

	if len(ret) == 0 {
		panic("no return value specified for FindAutoApplicable")
	}

	var r0 *entity.PlatformDiscount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID, decimal.Decimal) (*entity.PlatformDiscount, error)); ok {
		return rf(ctx, db, clientID, planID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID, decimal.Decimal) *entity.PlatformDiscount); ok {
		r0 = rf(ctx, db, clientID, planID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PlatformDiscount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID, decimal.Decimal) error); ok {
		r1 = rf(ctx, db, clientID, planID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByCode provides a mock function with given fields: ctx, db, code
func (_m *IPlatformDiscountRepository) FindByCode(ctx context.Context, db *gorm.DB, code string) (*entity.PlatformDiscount, error) {
	ret := _m.Called(ctx, db, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *entity.PlatformDiscount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (*entity.PlatformDiscount, error)); ok {
		return rf(ctx, db, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) *entity.PlatformDiscount); ok {
		r0 = rf(ctx, db, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PlatformDiscount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = rf(ctx, db, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, db, id
func (_m *IPlatformDiscountRepository) FindByID(ctx context.Context, db *gorm.DB, id uuid.UUID) (*entity.PlatformDiscount, error) {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.PlatformDiscount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.PlatformDiscount, error)); ok {
		return rf(ctx, db, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.PlatformDiscount); ok {
		r0 = rf(ctx, db, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PlatformDiscount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, db, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementUsage provides a mock function with given fields: ctx, db, id
func (_m *IPlatformDiscountRepository) IncrementUsage(ctx context.Context, db *gorm.DB, id uuid.UUID) error {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r0 = rf(ctx, db, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecrementUsage provides a mock function with given fields: ctx, db, id
func (_m *IPlatformDiscountRepository) DecrementUsage(ctx context.Context, db *gorm.DB, id uuid.UUID) error {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for DecrementUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r0 = rf(ctx, db, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SoftDelete provides a mock function with given fields: ctx, db, id
func (_m *IPlatformDiscountRepository) SoftDelete(ctx context.Context, db *gorm.DB, id uuid.UUID) error {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r0 = rf(ctx, db, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, db, d
func (_m *IPlatformDiscountRepository) Update(ctx context.Context, db *gorm.DB, d *entity.PlatformDiscount) error {
	ret := _m.Called(ctx, db, d)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.PlatformDiscount) error); ok {
		r0 = rf(ctx, db, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIPlatformDiscountRepository creates a new instance of IPlatformDiscountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPlatformDiscountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPlatformDiscountRepository {
	mock := &IPlatformDiscountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
