// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IPlatformPlanRepository is an autogenerated mock type for the IPlatformPlanRepository type
type IPlatformPlanRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, db, plan
func (_m *IPlatformPlanRepository) Create(ctx context.Context, db *gorm.DB, plan *entity.PlatformPlan) error {
	ret := _m.Called(ctx, db, plan)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.PlatformPlan) error); ok {
		r0 = rf(ctx, db, plan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, db, id
func (_m *IPlatformPlanRepository) Delete(ctx context.Context, db *gorm.DB, id uuid.UUID) error {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r0 = rf(ctx, db, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindActiveByName provides a mock function with given fields: ctx, tx, name
func (_m *IPlatformPlanRepository) FindActiveByName(ctx context.Context, tx *gorm.DB, name string) (*entity.PlatformPlan, error) {
	ret := _m.Called(ctx, tx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByName")
	}

	var r0 *entity.PlatformPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (*entity.PlatformPlan, error)); ok {
		return rf(ctx, tx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) *entity.PlatformPlan); ok {
		r0 = rf(ctx, tx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PlatformPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = rf(ctx, tx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, db, onlyActive
func (_m *IPlatformPlanRepository) FindAll(ctx context.Context, db *gorm.DB, onlyActive bool) ([]entity.PlatformPlan, error) {
	ret := _m.Called(ctx, db, onlyActive)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.PlatformPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, bool) ([]entity.PlatformPlan, error)); ok {
		return rf(ctx, db, onlyActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, bool) []entity.PlatformPlan); ok {
		r0 = rf(ctx, db, onlyActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PlatformPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, bool) error); ok {
		r1 = rf(ctx, db, onlyActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllActive provides a mock function with given fields: ctx, tx
func (_m *IPlatformPlanRepository) FindAllActive(ctx context.Context, tx *gorm.DB) ([]entity.PlatformPlan, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for FindAllActive")
	}

	var r0 []entity.PlatformPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]entity.PlatformPlan, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []entity.PlatformPlan); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PlatformPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllWithInactive provides a mock function with given fields: ctx, tx
func (_m *IPlatformPlanRepository) FindAllWithInactive(ctx context.Context, tx *gorm.DB) ([]entity.PlatformPlan, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for FindAllWithInactive")
	}

	var r0 []entity.PlatformPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]entity.PlatformPlan, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []entity.PlatformPlan); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PlatformPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, db, id
func (_m *IPlatformPlanRepository) FindByID(ctx context.Context, db *gorm.DB, id uuid.UUID) (*entity.PlatformPlan, error) {
	ret := _m.Called(ctx, db, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.PlatformPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.PlatformPlan, error)); ok {
		return rf(ctx, db, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.PlatformPlan); ok {
		r0 = rf(ctx, db, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PlatformPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, db, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: ctx, db, name
func (_m *IPlatformPlanRepository) FindByName(ctx context.Context, db *gorm.DB, name string) (*entity.PlatformPlan, error) {
	ret := _m.Called(ctx, db, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *entity.PlatformPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (*entity.PlatformPlan, error)); ok {
		return rf(ctx, db, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) *entity.PlatformPlan); ok {
		r0 = rf(ctx, db, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PlatformPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = rf(ctx, db, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsNameTaken provides a mock function with given fields: ctx, db, name, excludeID
func (_m *IPlatformPlanRepository) IsNameTaken(ctx context.Context, db *gorm.DB, name string, excludeID *uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, db, name, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for IsNameTaken")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string, *uuid.UUID) (bool, error)); ok {
		return rf(ctx, db, name, excludeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string, *uuid.UUID) bool); ok {
		r0 = rf(ctx, db, name, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string, *uuid.UUID) error); ok {
		r1 = rf(ctx, db, name, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, db, plan
func (_m *IPlatformPlanRepository) Update(ctx context.Context, db *gorm.DB, plan *entity.PlatformPlan) error {
	ret := _m.Called(ctx, db, plan)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.PlatformPlan) error); ok {
		r0 = rf(ctx, db, plan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIPlatformPlanRepository creates a new instance of IPlatformPlanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPlatformPlanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPlatformPlanRepository {
	mock := &IPlatformPlanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
