// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ISubscriptionRepository is an autogenerated mock type for the ISubscriptionRepository type
type ISubscriptionRepository struct {
	mock.Mock
}

// CountById provides a mock function with given fields: ctx, tx, id
func (_m *ISubscriptionRepository) CountById(ctx context.Context, tx *gorm.DB, id interface{}) (int64, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountById")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) (int64, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) int64); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, interface{}) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, tx, subscription
func (_m *ISubscriptionRepository) Create(ctx context.Context, tx *gorm.DB, subscription *entity.Subscription) error {
	ret := _m.Called(ctx, tx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Subscription) error); ok {
		r0 = rf(ctx, tx, subscription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tx, _a2
func (_m *ISubscriptionRepository) Delete(ctx context.Context, tx *gorm.DB, _a2 *entity.Subscription) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Subscription) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, tx
func (_m *ISubscriptionRepository) FindAll(ctx context.Context, tx *gorm.DB) ([]entity.Subscription, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]entity.Subscription, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []entity.Subscription); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, tx, _a2, id
func (_m *ISubscriptionRepository) FindById(ctx context.Context, tx *gorm.DB, _a2 *entity.Subscription, id interface{}) error {
	ret := _m.Called(ctx, tx, _a2, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Subscription, interface{}) error); ok {
		r0 = rf(ctx, tx, _a2, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByUserAndPackage provides a mock function with given fields: ctx, tx, userID, packageID
func (_m *ISubscriptionRepository) FindByUserAndPackage(ctx context.Context, tx *gorm.DB, userID uuid.UUID, packageID uuid.UUID) (*entity.Subscription, error) {
	ret := _m.Called(ctx, tx, userID, packageID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserAndPackage")
	}

	var r0 *entity.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID) (*entity.Subscription, error)); ok {
		return rf(ctx, tx, userID, packageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID) *entity.Subscription); ok {
		r0 = rf(ctx, tx, userID, packageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, userID, packageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindExpiredSubscriptions provides a mock function with given fields: ctx, tx, limit
func (_m *ISubscriptionRepository) FindExpiredSubscriptions(ctx context.Context, tx *gorm.DB, limit int) ([]entity.Subscription, error) {
	ret := _m.Called(ctx, tx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindExpiredSubscriptions")
	}

	var r0 []entity.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int) ([]entity.Subscription, error)); ok {
		return rf(ctx, tx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int) []entity.Subscription); ok {
		r0 = rf(ctx, tx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int) error); ok {
		r1 = rf(ctx, tx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasActiveSubscriptionForGroup provides a mock function with given fields: ctx, tx, telegramUserID, telegramChatID
func (_m *ISubscriptionRepository) HasActiveSubscriptionForGroup(ctx context.Context, tx *gorm.DB, telegramUserID int64, telegramChatID int64) (bool, error) {
	ret := _m.Called(ctx, tx, telegramUserID, telegramChatID)

	if len(ret) == 0 {
		panic("no return value specified for HasActiveSubscriptionForGroup")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, int64) (bool, error)); ok {
		return rf(ctx, tx, telegramUserID, telegramChatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, int64) bool); ok {
		r0 = rf(ctx, tx, telegramUserID, telegramChatID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int64, int64) error); ok {
		r1 = rf(ctx, tx, telegramUserID, telegramChatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, tx, subscription
func (_m *ISubscriptionRepository) Update(ctx context.Context, tx *gorm.DB, subscription *entity.Subscription) error {
	ret := _m.Called(ctx, tx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Subscription) error); ok {
		r0 = rf(ctx, tx, subscription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewISubscriptionRepository creates a new instance of ISubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISubscriptionRepository {
	mock := &ISubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
