// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ITelegramGroupRepository is an autogenerated mock type for the ITelegramGroupRepository type
type ITelegramGroupRepository struct {
	mock.Mock
}

// CountById provides a mock function with given fields: ctx, tx, id
func (_m *ITelegramGroupRepository) CountById(ctx context.Context, tx *gorm.DB, id interface{}) (int64, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountById")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) (int64, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) int64); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, interface{}) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, tx, _a2
func (_m *ITelegramGroupRepository) Create(ctx context.Context, tx *gorm.DB, _a2 *entity.Group) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Group) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tx, group
func (_m *ITelegramGroupRepository) Delete(ctx context.Context, tx *gorm.DB, group *entity.Group) error {
	ret := _m.Called(ctx, tx, group)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Group) error); ok {
		r0 = rf(ctx, tx, group)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, tx
func (_m *ITelegramGroupRepository) FindAll(ctx context.Context, tx *gorm.DB) ([]entity.Group, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]entity.Group, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []entity.Group); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByBotID provides a mock function with given fields: ctx, tx, botID
func (_m *ITelegramGroupRepository) FindByBotID(ctx context.Context, tx *gorm.DB, botID uuid.UUID) ([]entity.Group, error) {
	ret := _m.Called(ctx, tx, botID)

	if len(ret) == 0 {
		panic("no return value specified for FindByBotID")
	}

	var r0 []entity.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) ([]entity.Group, error)); ok {
		return rf(ctx, tx, botID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) []entity.Group); ok {
		r0 = rf(ctx, tx, botID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, botID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByClientID provides a mock function with given fields: ctx, tx, clientID
func (_m *ITelegramGroupRepository) FindByClientID(ctx context.Context, tx *gorm.DB, clientID uuid.UUID) ([]entity.Group, error) {
	ret := _m.Called(ctx, tx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for FindByClientID")
	}

	var r0 []entity.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) ([]entity.Group, error)); ok {
		return rf(ctx, tx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) []entity.Group); ok {
		r0 = rf(ctx, tx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, tx, id
func (_m *ITelegramGroupRepository) FindByID(ctx context.Context, tx *gorm.DB, id uuid.UUID) (*entity.Group, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.Group, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.Group); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, tx, _a2, id
func (_m *ITelegramGroupRepository) FindById(ctx context.Context, tx *gorm.DB, _a2 *entity.Group, id interface{}) error {
	ret := _m.Called(ctx, tx, _a2, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Group, interface{}) error); ok {
		r0 = rf(ctx, tx, _a2, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByTelegramID provides a mock function with given fields: ctx, tx, telegramID
func (_m *ITelegramGroupRepository) FindByTelegramID(ctx context.Context, tx *gorm.DB, telegramID int64) (*entity.Group, error) {
	ret := _m.Called(ctx, tx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for FindByTelegramID")
	}

	var r0 *entity.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64) (*entity.Group, error)); ok {
		return rf(ctx, tx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64) *entity.Group); ok {
		r0 = rf(ctx, tx, telegramID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int64) error); ok {
		r1 = rf(ctx, tx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, tx, _a2
func (_m *ITelegramGroupRepository) Update(ctx context.Context, tx *gorm.DB, _a2 *entity.Group) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.Group) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewITelegramGroupRepository creates a new instance of ITelegramGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITelegramGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITelegramGroupRepository {
	mock := &ITelegramGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
