// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ITelegramBotRepository is an autogenerated mock type for the ITelegramBotRepository type
type ITelegramBotRepository struct {
	mock.Mock
}

// CountById provides a mock function with given fields: ctx, tx, id
func (_m *ITelegramBotRepository) CountById(ctx context.Context, tx *gorm.DB, id interface{}) (int64, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for CountById")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) (int64, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, interface{}) int64); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, interface{}) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, tx, _a2
func (_m *ITelegramBotRepository) Create(ctx context.Context, tx *gorm.DB, _a2 *entity.TelegramBot) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.TelegramBot) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tx, bot
func (_m *ITelegramBotRepository) Delete(ctx context.Context, tx *gorm.DB, bot *entity.TelegramBot) error {
	ret := _m.Called(ctx, tx, bot)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.TelegramBot) error); ok {
		r0 = rf(ctx, tx, bot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, tx
func (_m *ITelegramBotRepository) FindAll(ctx context.Context, tx *gorm.DB) ([]entity.TelegramBot, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.TelegramBot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]entity.TelegramBot, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []entity.TelegramBot); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TelegramBot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByBotID provides a mock function with given fields: ctx, tx, botID
func (_m *ITelegramBotRepository) FindByBotID(ctx context.Context, tx *gorm.DB, botID int64) (*entity.TelegramBot, error) {
	ret := _m.Called(ctx, tx, botID)

	if len(ret) == 0 {
		panic("no return value specified for FindByBotID")
	}

	var r0 *entity.TelegramBot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64) (*entity.TelegramBot, error)); ok {
		return rf(ctx, tx, botID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64) *entity.TelegramBot); ok {
		r0 = rf(ctx, tx, botID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TelegramBot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int64) error); ok {
		r1 = rf(ctx, tx, botID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByClientID provides a mock function with given fields: ctx, tx, clientID
func (_m *ITelegramBotRepository) FindByClientID(ctx context.Context, tx *gorm.DB, clientID uuid.UUID) ([]entity.TelegramBot, error) {
	ret := _m.Called(ctx, tx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for FindByClientID")
	}

	var r0 []entity.TelegramBot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) ([]entity.TelegramBot, error)); ok {
		return rf(ctx, tx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) []entity.TelegramBot); ok {
		r0 = rf(ctx, tx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TelegramBot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindFirstByClientID provides a mock function with given fields: ctx, tx, clientID
func (_m *ITelegramBotRepository) FindFirstByClientID(ctx context.Context, tx *gorm.DB, clientID uuid.UUID) (*entity.TelegramBot, error) {
	ret := _m.Called(ctx, tx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for FindFirstByClientID")
	}

	var r0 *entity.TelegramBot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.TelegramBot, error)); ok {
		return rf(ctx, tx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.TelegramBot); ok {
		r0 = rf(ctx, tx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TelegramBot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, tx, id
func (_m *ITelegramBotRepository) FindByID(ctx context.Context, tx *gorm.DB, id uuid.UUID) (*entity.TelegramBot, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.TelegramBot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (*entity.TelegramBot, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) *entity.TelegramBot); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TelegramBot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: ctx, tx, _a2, id
func (_m *ITelegramBotRepository) FindById(ctx context.Context, tx *gorm.DB, _a2 *entity.TelegramBot, id interface{}) error {
	ret := _m.Called(ctx, tx, _a2, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.TelegramBot, interface{}) error); ok {
		r0 = rf(ctx, tx, _a2, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, tx, _a2
func (_m *ITelegramBotRepository) Update(ctx context.Context, tx *gorm.DB, _a2 *entity.TelegramBot) error {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.TelegramBot) error); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewITelegramBotRepository creates a new instance of ITelegramBotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITelegramBotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITelegramBotRepository {
	mock := &ITelegramBotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
