// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Fadlihardiyanto/telegram-management-app/internal/entity"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// ITenantPermissionRepository is an autogenerated mock type for the ITenantPermissionRepository type
type ITenantPermissionRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: ctx, db
func (_m *ITenantPermissionRepository) FindAll(ctx context.Context, db *gorm.DB) ([]entity.Permission, error) {
	ret := _m.Called(ctx, db)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]entity.Permission, error)); ok {
		return rf(ctx, db)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []entity.Permission); ok {
		r0 = rf(ctx, db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, db)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPermissionNamesByRole provides a mock function with given fields: ctx, db, roleName
func (_m *ITenantPermissionRepository) FindPermissionNamesByRole(ctx context.Context, db *gorm.DB, roleName string) ([]string, error) {
	ret := _m.Called(ctx, db, roleName)

	if len(ret) == 0 {
		panic("no return value specified for FindPermissionNamesByRole")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) ([]string, error)); ok {
		return rf(ctx, db, roleName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) []string); ok {
		r0 = rf(ctx, db, roleName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = rf(ctx, db, roleName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewITenantPermissionRepository creates a new instance of ITenantPermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITenantPermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITenantPermissionRepository {
	mock := &ITenantPermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
