// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IAdminBillingUseCase is an autogenerated mock type for the IAdminBillingUseCase type
type IAdminBillingUseCase struct {
	mock.Mock
}

// AssignPlan provides a mock function with given fields: ctx, req
func (_m *IAdminBillingUseCase) AssignPlan(ctx context.Context, req *model.AdminAssignPlanRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AssignPlan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminAssignPlanRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListPlans provides a mock function with given fields: ctx, req
func (_m *IAdminBillingUseCase) ListPlans(ctx context.Context, req *model.AdminListPlansRequest) ([]model.PlatformPlanResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListPlans")
	}

	var r0 []model.PlatformPlanResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminListPlansRequest) ([]model.PlatformPlanResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminListPlansRequest) []model.PlatformPlanResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PlatformPlanResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminListPlansRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAdminBillingUseCase creates a new instance of IAdminBillingUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdminBillingUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdminBillingUseCase {
	mock := &IAdminBillingUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
