// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IAdminTenantUserUseCase is an autogenerated mock type for the IAdminTenantUserUseCase type
type IAdminTenantUserUseCase struct {
	mock.Mock
}

// CreateTenantUser provides a mock function with given fields: ctx, req
func (_m *IAdminTenantUserUseCase) CreateTenantUser(ctx context.Context, req *model.AdminTenantUserCreateRequest) (*model.TenantUserResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTenantUser")
	}

	var r0 *model.TenantUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminTenantUserCreateRequest) (*model.TenantUserResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminTenantUserCreateRequest) *model.TenantUserResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TenantUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminTenantUserCreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTenantUser provides a mock function with given fields: ctx, req
func (_m *IAdminTenantUserUseCase) DeleteTenantUser(ctx context.Context, req *model.AdminTenantUserDeleteRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTenantUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminTenantUserDeleteRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTenantUser provides a mock function with given fields: ctx, req
func (_m *IAdminTenantUserUseCase) GetTenantUser(ctx context.Context, req *model.AdminTenantUserGetRequest) (*model.TenantUserResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantUser")
	}

	var r0 *model.TenantUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminTenantUserGetRequest) (*model.TenantUserResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminTenantUserGetRequest) *model.TenantUserResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TenantUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminTenantUserGetRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTenantUsers provides a mock function with given fields: ctx, req
func (_m *IAdminTenantUserUseCase) ListTenantUsers(ctx context.Context, req *model.AdminTenantUserListRequest) ([]model.TenantUserResponse, int64, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListTenantUsers")
	}

	var r0 []model.TenantUserResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminTenantUserListRequest) ([]model.TenantUserResponse, int64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminTenantUserListRequest) []model.TenantUserResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TenantUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminTenantUserListRequest) int64); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *model.AdminTenantUserListRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateTenantUser provides a mock function with given fields: ctx, req
func (_m *IAdminTenantUserUseCase) UpdateTenantUser(ctx context.Context, req *model.AdminTenantUserUpdateRequest) (*model.TenantUserResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTenantUser")
	}

	var r0 *model.TenantUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminTenantUserUpdateRequest) (*model.TenantUserResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminTenantUserUpdateRequest) *model.TenantUserResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TenantUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminTenantUserUpdateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAdminTenantUserUseCase creates a new instance of IAdminTenantUserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdminTenantUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdminTenantUserUseCase {
	mock := &IAdminTenantUserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
