// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IAdminAnalyticsUseCase is an autogenerated mock type for the IAdminAnalyticsUseCase type
type IAdminAnalyticsUseCase struct {
	mock.Mock
}

// GetPlatformOverview provides a mock function with given fields: ctx, req
func (_m *IAdminAnalyticsUseCase) GetPlatformOverview(ctx context.Context, req *model.AdminPlatformOverviewRequest) (interface{}, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetPlatformOverview")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminPlatformOverviewRequest) (interface{}, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminPlatformOverviewRequest) interface{}); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminPlatformOverviewRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRevenueReport provides a mock function with given fields: ctx, req
func (_m *IAdminAnalyticsUseCase) GetRevenueReport(ctx context.Context, req *model.AdminRevenueReportRequest) (interface{}, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetRevenueReport")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminRevenueReportRequest) (interface{}, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminRevenueReportRequest) interface{}); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminRevenueReportRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAdminAnalyticsUseCase creates a new instance of IAdminAnalyticsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdminAnalyticsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdminAnalyticsUseCase {
	mock := &IAdminAnalyticsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
