// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IAdminUserManagementUseCase is an autogenerated mock type for the IAdminUserManagementUseCase type
type IAdminUserManagementUseCase struct {
	mock.Mock
}

// ActivateAdmin provides a mock function with given fields: ctx, req
func (_m *IAdminUserManagementUseCase) ActivateAdmin(ctx context.Context, req *model.AdminUserActivateRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ActivateAdmin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminUserActivateRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateAdmin provides a mock function with given fields: ctx, req
func (_m *IAdminUserManagementUseCase) CreateAdmin(ctx context.Context, req *model.AdminUserCreateRequest) (*model.AdminUserResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateAdmin")
	}

	var r0 *model.AdminUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminUserCreateRequest) (*model.AdminUserResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminUserCreateRequest) *model.AdminUserResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminUserCreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeactivateAdmin provides a mock function with given fields: ctx, req
func (_m *IAdminUserManagementUseCase) DeactivateAdmin(ctx context.Context, req *model.AdminUserDeactivateRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateAdmin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminUserDeactivateRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAdmin provides a mock function with given fields: ctx, req
func (_m *IAdminUserManagementUseCase) DeleteAdmin(ctx context.Context, req *model.AdminUserDeleteRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAdmin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminUserDeleteRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAdmin provides a mock function with given fields: ctx, req
func (_m *IAdminUserManagementUseCase) GetAdmin(ctx context.Context, req *model.AdminUserGetRequest) (*model.AdminUserResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetAdmin")
	}

	var r0 *model.AdminUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminUserGetRequest) (*model.AdminUserResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminUserGetRequest) *model.AdminUserResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminUserGetRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAdmins provides a mock function with given fields: ctx, req
func (_m *IAdminUserManagementUseCase) ListAdmins(ctx context.Context, req *model.AdminUserListRequest) ([]model.AdminUserResponse, int64, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListAdmins")
	}

	var r0 []model.AdminUserResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminUserListRequest) ([]model.AdminUserResponse, int64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminUserListRequest) []model.AdminUserResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AdminUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminUserListRequest) int64); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *model.AdminUserListRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateAdmin provides a mock function with given fields: ctx, req
func (_m *IAdminUserManagementUseCase) UpdateAdmin(ctx context.Context, req *model.AdminUserUpdateRequest) (*model.AdminUserResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAdmin")
	}

	var r0 *model.AdminUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminUserUpdateRequest) (*model.AdminUserResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminUserUpdateRequest) *model.AdminUserResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminUserUpdateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAdminUserManagementUseCase creates a new instance of IAdminUserManagementUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdminUserManagementUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdminUserManagementUseCase {
	mock := &IAdminUserManagementUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
