// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IAdminRoleUseCase is an autogenerated mock type for the IAdminRoleUseCase type
type IAdminRoleUseCase struct {
	mock.Mock
}

// AssignRoleToAdmin provides a mock function with given fields: ctx, req
func (_m *IAdminRoleUseCase) AssignRoleToAdmin(ctx context.Context, req *model.AdminAssignRoleRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AssignRoleToAdmin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminAssignRoleRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AssignRolesToAdmin provides a mock function with given fields: ctx, req
func (_m *IAdminRoleUseCase) AssignRolesToAdmin(ctx context.Context, req *model.AdminAssignRolesRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AssignRolesToAdmin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminAssignRolesRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRole provides a mock function with given fields: ctx, req
func (_m *IAdminRoleUseCase) CreateRole(ctx context.Context, req *model.AdminRoleCreateRequest) (*model.AdminRoleResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 *model.AdminRoleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminRoleCreateRequest) (*model.AdminRoleResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminRoleCreateRequest) *model.AdminRoleResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminRoleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminRoleCreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRole provides a mock function with given fields: ctx, req
func (_m *IAdminRoleUseCase) DeleteRole(ctx context.Context, req *model.AdminRoleDeleteRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminRoleDeleteRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRole provides a mock function with given fields: ctx, req
func (_m *IAdminRoleUseCase) GetRole(ctx context.Context, req *model.AdminRoleGetRequest) (*model.AdminRoleResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 *model.AdminRoleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminRoleGetRequest) (*model.AdminRoleResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminRoleGetRequest) *model.AdminRoleResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminRoleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminRoleGetRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRoles provides a mock function with given fields: ctx, req
func (_m *IAdminRoleUseCase) ListRoles(ctx context.Context, req *model.AdminRoleListRequest) ([]model.AdminRoleResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListRoles")
	}

	var r0 []model.AdminRoleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminRoleListRequest) ([]model.AdminRoleResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminRoleListRequest) []model.AdminRoleResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AdminRoleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminRoleListRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeRoleFromAdmin provides a mock function with given fields: ctx, req
func (_m *IAdminRoleUseCase) RevokeRoleFromAdmin(ctx context.Context, req *model.AdminRevokeRoleRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRoleFromAdmin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminRevokeRoleRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SyncRolePermissions provides a mock function with given fields: ctx, req
func (_m *IAdminRoleUseCase) SyncRolePermissions(ctx context.Context, req *model.AdminSyncPermissionsRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SyncRolePermissions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminSyncPermissionsRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRole provides a mock function with given fields: ctx, req
func (_m *IAdminRoleUseCase) UpdateRole(ctx context.Context, req *model.AdminRoleUpdateRequest) (*model.AdminRoleResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 *model.AdminRoleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminRoleUpdateRequest) (*model.AdminRoleResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminRoleUpdateRequest) *model.AdminRoleResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminRoleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminRoleUpdateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAdminRoleUseCase creates a new instance of IAdminRoleUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdminRoleUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdminRoleUseCase {
	mock := &IAdminRoleUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
