// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IAdminAuthUseCase is an autogenerated mock type for the IAdminAuthUseCase type
type IAdminAuthUseCase struct {
	mock.Mock
}

// Enable2FA provides a mock function with given fields: ctx, req
func (_m *IAdminAuthUseCase) Enable2FA(ctx context.Context, req *model.AdminEnable2FARequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Enable2FA")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminEnable2FARequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: ctx, req
func (_m *IAdminAuthUseCase) Login(ctx context.Context, req *model.AdminLoginRequest) (*model.AdminLoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.AdminLoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminLoginRequest) (*model.AdminLoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminLoginRequest) *model.AdminLoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminLoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminLoginRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: ctx, req
func (_m *IAdminAuthUseCase) Logout(ctx context.Context, req *model.AdminLogoutRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminLogoutRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshToken provides a mock function with given fields: ctx, req
func (_m *IAdminAuthUseCase) RefreshToken(ctx context.Context, req *model.AdminRefreshTokenRequest) (*model.AdminLoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *model.AdminLoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminRefreshTokenRequest) (*model.AdminLoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminRefreshTokenRequest) *model.AdminLoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminLoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminRefreshTokenRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, req
func (_m *IAdminAuthUseCase) Register(ctx context.Context, req *model.AdminUserCreateRequest) (*model.AdminUserResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *model.AdminUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminUserCreateRequest) (*model.AdminUserResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminUserCreateRequest) *model.AdminUserResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminUserCreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Setup2FA provides a mock function with given fields: ctx, req
func (_m *IAdminAuthUseCase) Setup2FA(ctx context.Context, req *model.AdminSetup2FARequest) (*model.Admin2FASetupResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Setup2FA")
	}

	var r0 *model.Admin2FASetupResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminSetup2FARequest) (*model.Admin2FASetupResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminSetup2FARequest) *model.Admin2FASetupResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Admin2FASetupResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminSetup2FARequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Verify2FA provides a mock function with given fields: ctx, req
func (_m *IAdminAuthUseCase) Verify2FA(ctx context.Context, req *model.AdminVerify2FARequest) (*model.AdminLoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Verify2FA")
	}

	var r0 *model.AdminLoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminVerify2FARequest) (*model.AdminLoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminVerify2FARequest) *model.AdminLoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminLoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminVerify2FARequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyEmail provides a mock function with given fields: ctx, req
func (_m *IAdminAuthUseCase) VerifyEmail(ctx context.Context, req *model.AdminVerifyEmailRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminVerifyEmailRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAdminAuthUseCase creates a new instance of IAdminAuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdminAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdminAuthUseCase {
	mock := &IAdminAuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
