// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IAdminTenantUseCase is an autogenerated mock type for the IAdminTenantUseCase type
type IAdminTenantUseCase struct {
	mock.Mock
}

// ActivateClient provides a mock function with given fields: ctx, req
func (_m *IAdminTenantUseCase) ActivateClient(ctx context.Context, req *model.AdminActivateClientRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ActivateClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminActivateClientRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateClient provides a mock function with given fields: ctx, req
func (_m *IAdminTenantUseCase) CreateClient(ctx context.Context, req *model.AdminCreateClientRequest) (*model.ClientResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateClient")
	}

	var r0 *model.ClientResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminCreateClientRequest) (*model.ClientResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminCreateClientRequest) *model.ClientResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClientResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminCreateClientRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeactivateClient provides a mock function with given fields: ctx, req
func (_m *IAdminTenantUseCase) DeactivateClient(ctx context.Context, req *model.AdminDeactivateClientRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminDeactivateClientRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteClient provides a mock function with given fields: ctx, req
func (_m *IAdminTenantUseCase) DeleteClient(ctx context.Context, req *model.AdminDeleteClientRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminDeleteClientRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetClientDetail provides a mock function with given fields: ctx, req
func (_m *IAdminTenantUseCase) GetClientDetail(ctx context.Context, req *model.AdminGetClientDetailRequest) (*model.ClientResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetClientDetail")
	}

	var r0 *model.ClientResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminGetClientDetailRequest) (*model.ClientResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminGetClientDetailRequest) *model.ClientResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClientResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminGetClientDetailRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAllClients provides a mock function with given fields: ctx, req
func (_m *IAdminTenantUseCase) ListAllClients(ctx context.Context, req *model.AdminListAllClientsRequest) ([]model.ClientResponse, int64, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListAllClients")
	}

	var r0 []model.ClientResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminListAllClientsRequest) ([]model.ClientResponse, int64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminListAllClientsRequest) []model.ClientResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ClientResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminListAllClientsRequest) int64); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *model.AdminListAllClientsRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateClient provides a mock function with given fields: ctx, req
func (_m *IAdminTenantUseCase) UpdateClient(ctx context.Context, req *model.AdminUpdateClientRequest) (*model.ClientResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClient")
	}

	var r0 *model.ClientResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminUpdateClientRequest) (*model.ClientResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminUpdateClientRequest) *model.ClientResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClientResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminUpdateClientRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAdminTenantUseCase creates a new instance of IAdminTenantUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdminTenantUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdminTenantUseCase {
	mock := &IAdminTenantUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
