// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IAdminPermissionUseCase is an autogenerated mock type for the IAdminPermissionUseCase type
type IAdminPermissionUseCase struct {
	mock.Mock
}

// GetPermission provides a mock function with given fields: ctx, req
func (_m *IAdminPermissionUseCase) GetPermission(ctx context.Context, req *model.AdminPermissionGetRequest) (*model.AdminPermissionResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetPermission")
	}

	var r0 *model.AdminPermissionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminPermissionGetRequest) (*model.AdminPermissionResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminPermissionGetRequest) *model.AdminPermissionResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminPermissionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminPermissionGetRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPermissions provides a mock function with given fields: ctx, req
func (_m *IAdminPermissionUseCase) ListPermissions(ctx context.Context, req *model.AdminPermissionListRequest) ([]model.AdminPermissionModuleGroupResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListPermissions")
	}

	var r0 []model.AdminPermissionModuleGroupResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminPermissionListRequest) ([]model.AdminPermissionModuleGroupResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminPermissionListRequest) []model.AdminPermissionModuleGroupResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AdminPermissionModuleGroupResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminPermissionListRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAdminPermissionUseCase creates a new instance of IAdminPermissionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdminPermissionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdminPermissionUseCase {
	mock := &IAdminPermissionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
