// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"

	uuid "github.com/google/uuid"
)

// IAuditLogUseCase is an autogenerated mock type for the IAuditLogUseCase type
type IAuditLogUseCase struct {
	mock.Mock
}

// GetLogsByClient provides a mock function with given fields: ctx, clientID, page, limit
func (_m *IAuditLogUseCase) GetLogsByClient(ctx context.Context, clientID uuid.UUID, page int, limit int) ([]model.AuditLogResponse, int64, error) {
	ret := _m.Called(ctx, clientID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLogsByClient")
	}

	var r0 []model.AuditLogResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]model.AuditLogResponse, int64, error)); ok {
		return rf(ctx, clientID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []model.AuditLogResponse); ok {
		r0 = rf(ctx, clientID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AuditLogResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int64); ok {
		r1 = rf(ctx, clientID, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, clientID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPlatformLogs provides a mock function with given fields: ctx, page, limit
func (_m *IAuditLogUseCase) GetPlatformLogs(ctx context.Context, page int, limit int) ([]model.AuditLogResponse, int64, error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPlatformLogs")
	}

	var r0 []model.AuditLogResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]model.AuditLogResponse, int64, error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []model.AuditLogResponse); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AuditLogResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Record provides a mock function with given fields: ctx, tx, clientID, entityType, entityID, action, actorType, actorID, metadata
func (_m *IAuditLogUseCase) Record(ctx context.Context, tx *gorm.DB, clientID *uuid.UUID, entityType string, entityID uuid.UUID, action string, actorType string, actorID string, metadata map[string]interface{}) error {
	ret := _m.Called(ctx, tx, clientID, entityType, entityID, action, actorType, actorID, metadata)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *uuid.UUID, string, uuid.UUID, string, string, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, tx, clientID, entityType, entityID, action, actorType, actorID, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAuditLogUseCase creates a new instance of IAuditLogUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuditLogUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuditLogUseCase {
	mock := &IAuditLogUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
