// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IClientBillingUseCase is an autogenerated mock type for the IClientBillingUseCase type
type IClientBillingUseCase struct {
	mock.Mock
}

// AdminAssignPlan provides a mock function with given fields: ctx, req
func (_m *IClientBillingUseCase) AdminAssignPlan(ctx context.Context, req *model.AdminAssignPlanRequest) (*model.ClientBillingResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AdminAssignPlan")
	}

	var r0 *model.ClientBillingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminAssignPlanRequest) (*model.ClientBillingResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminAssignPlanRequest) *model.ClientBillingResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClientBillingResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminAssignPlanRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelBilling provides a mock function with given fields: ctx, req
func (_m *IClientBillingUseCase) CancelBilling(ctx context.Context, req *model.CancelBillingRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CancelBilling")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CancelBillingRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Checkout provides a mock function with given fields: ctx, req
func (_m *IClientBillingUseCase) Checkout(ctx context.Context, req *model.ClientCheckoutPlanRequest) (*model.CheckoutResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 *model.CheckoutResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ClientCheckoutPlanRequest) (*model.CheckoutResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.ClientCheckoutPlanRequest) *model.CheckoutResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CheckoutResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.ClientCheckoutPlanRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveBilling provides a mock function with given fields: ctx, clientID
func (_m *IClientBillingUseCase) GetActiveBilling(ctx context.Context, clientID uuid.UUID) (*model.ClientBillingResponse, error) {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveBilling")
	}

	var r0 *model.ClientBillingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.ClientBillingResponse, error)); ok {
		return rf(ctx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.ClientBillingResponse); ok {
		r0 = rf(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClientBillingResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleWebhook provides a mock function with given fields: ctx, req
func (_m *IClientBillingUseCase) HandleWebhook(ctx context.Context, req *model.MidtransWebhookRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for HandleWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.MidtransWebhookRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListBillings provides a mock function with given fields: ctx, req
func (_m *IClientBillingUseCase) ListBillings(ctx context.Context, req *model.AdminListBillingRequest) ([]model.ClientBillingResponse, int64, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListBillings")
	}

	var r0 []model.ClientBillingResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminListBillingRequest) ([]model.ClientBillingResponse, int64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.AdminListBillingRequest) []model.ClientBillingResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ClientBillingResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.AdminListBillingRequest) int64); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *model.AdminListBillingRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewIClientBillingUseCase creates a new instance of IClientBillingUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIClientBillingUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IClientBillingUseCase {
	mock := &IClientBillingUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
