// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IMemberUseCase is an autogenerated mock type for the IMemberUseCase type
type IMemberUseCase struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: ctx, clientID, filter
func (_m *IMemberUseCase) FindAll(ctx context.Context, clientID uuid.UUID, filter model.MemberFilterRequest) ([]model.MemberResponse, int64, error) {
	ret := _m.Called(ctx, clientID, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.MemberResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.MemberFilterRequest) ([]model.MemberResponse, int64, error)); ok {
		return rf(ctx, clientID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.MemberFilterRequest) []model.MemberResponse); ok {
		r0 = rf(ctx, clientID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MemberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.MemberFilterRequest) int64); ok {
		r1 = rf(ctx, clientID, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, model.MemberFilterRequest) error); ok {
		r2 = rf(ctx, clientID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, clientID, userID
func (_m *IMemberUseCase) FindByID(ctx context.Context, clientID uuid.UUID, userID uuid.UUID) (*model.MemberDetailResponse, error) {
	ret := _m.Called(ctx, clientID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.MemberDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.MemberDetailResponse, error)); ok {
		return rf(ctx, clientID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.MemberDetailResponse); ok {
		r0 = rf(ctx, clientID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MemberDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, clientID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIMemberUseCase creates a new instance of IMemberUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMemberUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMemberUseCase {
	mock := &IMemberUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
