// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"

	uuid "github.com/google/uuid"
)

// IMemberDiscountUseCase is an autogenerated mock type for the IMemberDiscountUseCase type
type IMemberDiscountUseCase struct {
	mock.Mock
}

// ApplyAuto provides a mock function with given fields: ctx, req
func (_m *IMemberDiscountUseCase) ApplyAuto(ctx context.Context, req *model.ApplyMemberDiscountRequest) (*model.DiscountPreviewResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ApplyAuto")
	}

	var r0 *model.DiscountPreviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ApplyMemberDiscountRequest) (*model.DiscountPreviewResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.ApplyMemberDiscountRequest) *model.DiscountPreviewResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DiscountPreviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.ApplyMemberDiscountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApplyByCode provides a mock function with given fields: ctx, req
func (_m *IMemberDiscountUseCase) ApplyByCode(ctx context.Context, req *model.ApplyMemberDiscountRequest) (*model.DiscountPreviewResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ApplyByCode")
	}

	var r0 *model.DiscountPreviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ApplyMemberDiscountRequest) (*model.DiscountPreviewResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.ApplyMemberDiscountRequest) *model.DiscountPreviewResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DiscountPreviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.ApplyMemberDiscountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommitUsage provides a mock function with given fields: ctx, tx, discountID, telegramUserID, orderID, discountAmount
func (_m *IMemberDiscountUseCase) CommitUsage(ctx context.Context, tx *gorm.DB, discountID uuid.UUID, telegramUserID uuid.UUID, orderID uuid.UUID, discountAmount decimal.Decimal) error {
	ret := _m.Called(ctx, tx, discountID, telegramUserID, orderID, discountAmount)

	if len(ret) == 0 {
		panic("no return value specified for CommitUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID, uuid.UUID, decimal.Decimal) error); ok {
		r0 = rf(ctx, tx, discountID, telegramUserID, orderID, discountAmount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, req
func (_m *IMemberDiscountUseCase) Create(ctx context.Context, req *model.CreateMemberDiscountRequest) (*model.MemberDiscountResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.MemberDiscountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateMemberDiscountRequest) (*model.MemberDiscountResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateMemberDiscountRequest) *model.MemberDiscountResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MemberDiscountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.CreateMemberDiscountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id, clientID
func (_m *IMemberDiscountUseCase) Delete(ctx context.Context, id uuid.UUID, clientID uuid.UUID) error {
	ret := _m.Called(ctx, id, clientID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, clientID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListByClient provides a mock function with given fields: ctx, clientID, onlyActive
func (_m *IMemberDiscountUseCase) ListByClient(ctx context.Context, clientID uuid.UUID, onlyActive bool) ([]model.MemberDiscountResponse, error) {
	ret := _m.Called(ctx, clientID, onlyActive)

	if len(ret) == 0 {
		panic("no return value specified for ListByClient")
	}

	var r0 []model.MemberDiscountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) ([]model.MemberDiscountResponse, error)); ok {
		return rf(ctx, clientID, onlyActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) []model.MemberDiscountResponse); ok {
		r0 = rf(ctx, clientID, onlyActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MemberDiscountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, clientID, onlyActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RollbackUsage provides a mock function with given fields: ctx, tx, orderID, discountID
func (_m *IMemberDiscountUseCase) RollbackUsage(ctx context.Context, tx *gorm.DB, orderID uuid.UUID, discountID uuid.UUID) error {
	ret := _m.Called(ctx, tx, orderID, discountID)

	if len(ret) == 0 {
		panic("no return value specified for RollbackUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tx, orderID, discountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, req
func (_m *IMemberDiscountUseCase) Update(ctx context.Context, req *model.UpdateMemberDiscountRequest) (*model.MemberDiscountResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.MemberDiscountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UpdateMemberDiscountRequest) (*model.MemberDiscountResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.UpdateMemberDiscountRequest) *model.MemberDiscountResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MemberDiscountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.UpdateMemberDiscountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIMemberDiscountUseCase creates a new instance of IMemberDiscountUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMemberDiscountUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMemberDiscountUseCase {
	mock := &IMemberDiscountUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
