// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IMemberOrderUseCase is an autogenerated mock type for the IMemberOrderUseCase type
type IMemberOrderUseCase struct {
	mock.Mock
}

// Checkout provides a mock function with given fields: ctx, req
func (_m *IMemberOrderUseCase) Checkout(ctx context.Context, req *model.MemberCheckoutRequest) (*model.MemberCheckoutResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 *model.MemberCheckoutResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.MemberCheckoutRequest) (*model.MemberCheckoutResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.MemberCheckoutRequest) *model.MemberCheckoutResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MemberCheckoutResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.MemberCheckoutRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleWebhook provides a mock function with given fields: ctx, req
func (_m *IMemberOrderUseCase) HandleWebhook(ctx context.Context, req *model.MidtransWebhookRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for HandleWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.MidtransWebhookRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIMemberOrderUseCase creates a new instance of IMemberOrderUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMemberOrderUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMemberOrderUseCase {
	mock := &IMemberOrderUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
