// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IPackageUseCase is an autogenerated mock type for the IPackageUseCase type
type IPackageUseCase struct {
	mock.Mock
}

// AssociateGroups provides a mock function with given fields: ctx, clientID, packageID, req
func (_m *IPackageUseCase) AssociateGroups(ctx context.Context, clientID uuid.UUID, packageID uuid.UUID, req *model.PackageGroupAssociateRequest) error {
	ret := _m.Called(ctx, clientID, packageID, req)

	if len(ret) == 0 {
		panic("no return value specified for AssociateGroups")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.PackageGroupAssociateRequest) error); ok {
		r0 = rf(ctx, clientID, packageID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, clientID, req
func (_m *IPackageUseCase) Create(ctx context.Context, clientID uuid.UUID, req *model.PackageCreateRequest) (*model.PackageResponse, error) {
	ret := _m.Called(ctx, clientID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.PackageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.PackageCreateRequest) (*model.PackageResponse, error)); ok {
		return rf(ctx, clientID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.PackageCreateRequest) *model.PackageResponse); ok {
		r0 = rf(ctx, clientID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PackageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.PackageCreateRequest) error); ok {
		r1 = rf(ctx, clientID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, clientID, packageID
func (_m *IPackageUseCase) Delete(ctx context.Context, clientID uuid.UUID, packageID uuid.UUID) error {
	ret := _m.Called(ctx, clientID, packageID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, clientID, packageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllByClient provides a mock function with given fields: ctx, clientID
func (_m *IPackageUseCase) FindAllByClient(ctx context.Context, clientID uuid.UUID) ([]model.PackageResponse, error) {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByClient")
	}

	var r0 []model.PackageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.PackageResponse, error)); ok {
		return rf(ctx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.PackageResponse); ok {
		r0 = rf(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PackageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, clientID, packageID
func (_m *IPackageUseCase) FindByID(ctx context.Context, clientID uuid.UUID, packageID uuid.UUID) (*model.PackageResponse, error) {
	ret := _m.Called(ctx, clientID, packageID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.PackageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.PackageResponse, error)); ok {
		return rf(ctx, clientID, packageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.PackageResponse); ok {
		r0 = rf(ctx, clientID, packageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PackageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, clientID, packageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, clientID, packageID, req
func (_m *IPackageUseCase) Update(ctx context.Context, clientID uuid.UUID, packageID uuid.UUID, req *model.PackageUpdateRequest) (*model.PackageResponse, error) {
	ret := _m.Called(ctx, clientID, packageID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.PackageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.PackageUpdateRequest) (*model.PackageResponse, error)); ok {
		return rf(ctx, clientID, packageID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.PackageUpdateRequest) *model.PackageResponse); ok {
		r0 = rf(ctx, clientID, packageID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PackageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *model.PackageUpdateRequest) error); ok {
		r1 = rf(ctx, clientID, packageID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIPackageUseCase creates a new instance of IPackageUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPackageUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPackageUseCase {
	mock := &IPackageUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
