// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IPlatformPlanUseCase is an autogenerated mock type for the IPlatformPlanUseCase type
type IPlatformPlanUseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req, callerPermissions
func (_m *IPlatformPlanUseCase) Create(ctx context.Context, req *model.CreatePlatformPlanRequest, callerPermissions []string) (*model.PlatformPlanResponse, error) {
	ret := _m.Called(ctx, req, callerPermissions)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.PlatformPlanResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreatePlatformPlanRequest, []string) (*model.PlatformPlanResponse, error)); ok {
		return rf(ctx, req, callerPermissions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreatePlatformPlanRequest, []string) *model.PlatformPlanResponse); ok {
		r0 = rf(ctx, req, callerPermissions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PlatformPlanResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.CreatePlatformPlanRequest, []string) error); ok {
		r1 = rf(ctx, req, callerPermissions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id, callerPermissions
func (_m *IPlatformPlanUseCase) Delete(ctx context.Context, id uuid.UUID, callerPermissions []string) error {
	ret := _m.Called(ctx, id, callerPermissions)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) error); ok {
		r0 = rf(ctx, id, callerPermissions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id, callerPermissions
func (_m *IPlatformPlanUseCase) GetByID(ctx context.Context, id uuid.UUID, callerPermissions []string) (*model.PlatformPlanResponse, error) {
	ret := _m.Called(ctx, id, callerPermissions)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.PlatformPlanResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) (*model.PlatformPlanResponse, error)); ok {
		return rf(ctx, id, callerPermissions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) *model.PlatformPlanResponse); ok {
		r0 = rf(ctx, id, callerPermissions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PlatformPlanResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, []string) error); ok {
		r1 = rf(ctx, id, callerPermissions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, req, callerPermissions
func (_m *IPlatformPlanUseCase) List(ctx context.Context, req *model.PlatformPlanFilterRequest, callerPermissions []string) ([]model.PlatformPlanResponse, error) {
	ret := _m.Called(ctx, req, callerPermissions)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.PlatformPlanResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.PlatformPlanFilterRequest, []string) ([]model.PlatformPlanResponse, error)); ok {
		return rf(ctx, req, callerPermissions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.PlatformPlanFilterRequest, []string) []model.PlatformPlanResponse); ok {
		r0 = rf(ctx, req, callerPermissions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PlatformPlanResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.PlatformPlanFilterRequest, []string) error); ok {
		r1 = rf(ctx, req, callerPermissions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, req, callerPermissions
func (_m *IPlatformPlanUseCase) Update(ctx context.Context, id uuid.UUID, req *model.UpdatePlatformPlanRequest, callerPermissions []string) (*model.PlatformPlanResponse, error) {
	ret := _m.Called(ctx, id, req, callerPermissions)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.PlatformPlanResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.UpdatePlatformPlanRequest, []string) (*model.PlatformPlanResponse, error)); ok {
		return rf(ctx, id, req, callerPermissions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.UpdatePlatformPlanRequest, []string) *model.PlatformPlanResponse); ok {
		r0 = rf(ctx, id, req, callerPermissions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PlatformPlanResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.UpdatePlatformPlanRequest, []string) error); ok {
		r1 = rf(ctx, id, req, callerPermissions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIPlatformPlanUseCase creates a new instance of IPlatformPlanUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPlatformPlanUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPlatformPlanUseCase {
	mock := &IPlatformPlanUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
