// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"

	uuid "github.com/google/uuid"
)

// IPlatformDiscountUseCase is an autogenerated mock type for the IPlatformDiscountUseCase type
type IPlatformDiscountUseCase struct {
	mock.Mock
}

// ApplyAuto provides a mock function with given fields: ctx, clientID, planID, amount
func (_m *IPlatformDiscountUseCase) ApplyAuto(ctx context.Context, clientID uuid.UUID, planID uuid.UUID, amount decimal.Decimal) (*model.DiscountPreviewResponse, error) {
	ret := _m.Called(ctx, clientID, planID, amount)

	if len(ret) == 0 {
		panic("no return value specified for ApplyAuto")
	}

	var r0 *model.DiscountPreviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, decimal.Decimal) (*model.DiscountPreviewResponse, error)); ok {
		return rf(ctx, clientID, planID, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, decimal.Decimal) *model.DiscountPreviewResponse); ok {
		r0 = rf(ctx, clientID, planID, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DiscountPreviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, decimal.Decimal) error); ok {
		r1 = rf(ctx, clientID, planID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApplyByCode provides a mock function with given fields: ctx, req
func (_m *IPlatformDiscountUseCase) ApplyByCode(ctx context.Context, req *model.ApplyPlatformDiscountRequest) (*model.DiscountPreviewResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ApplyByCode")
	}

	var r0 *model.DiscountPreviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ApplyPlatformDiscountRequest) (*model.DiscountPreviewResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.ApplyPlatformDiscountRequest) *model.DiscountPreviewResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DiscountPreviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.ApplyPlatformDiscountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, req
func (_m *IPlatformDiscountUseCase) Create(ctx context.Context, req *model.CreatePlatformDiscountRequest) (*model.PlatformDiscountResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.PlatformDiscountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreatePlatformDiscountRequest) (*model.PlatformDiscountResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreatePlatformDiscountRequest) *model.PlatformDiscountResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PlatformDiscountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.CreatePlatformDiscountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id, callerPermissions
func (_m *IPlatformDiscountUseCase) Delete(ctx context.Context, id uuid.UUID, callerPermissions []string) error {
	ret := _m.Called(ctx, id, callerPermissions)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) error); ok {
		r0 = rf(ctx, id, callerPermissions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, onlyActive, callerPermissions
func (_m *IPlatformDiscountUseCase) List(ctx context.Context, onlyActive bool, callerPermissions []string) ([]model.PlatformDiscountResponse, error) {
	ret := _m.Called(ctx, onlyActive, callerPermissions)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.PlatformDiscountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, []string) ([]model.PlatformDiscountResponse, error)); ok {
		return rf(ctx, onlyActive, callerPermissions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool, []string) []model.PlatformDiscountResponse); ok {
		r0 = rf(ctx, onlyActive, callerPermissions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PlatformDiscountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool, []string) error); ok {
		r1 = rf(ctx, onlyActive, callerPermissions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, req
func (_m *IPlatformDiscountUseCase) Update(ctx context.Context, req *model.UpdatePlatformDiscountRequest) (*model.PlatformDiscountResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.PlatformDiscountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UpdatePlatformDiscountRequest) (*model.PlatformDiscountResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.UpdatePlatformDiscountRequest) *model.PlatformDiscountResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PlatformDiscountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.UpdatePlatformDiscountRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIPlatformDiscountUseCase creates a new instance of IPlatformDiscountUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPlatformDiscountUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPlatformDiscountUseCase {
	mock := &IPlatformDiscountUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
