// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ITelegramBotUseCase is an autogenerated mock type for the ITelegramBotUseCase type
type ITelegramBotUseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, clientID, req
func (_m *ITelegramBotUseCase) Create(ctx context.Context, clientID uuid.UUID, req *model.TelegramBotCreateRequest) (*model.TelegramBotResponse, error) {
	ret := _m.Called(ctx, clientID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.TelegramBotResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.TelegramBotCreateRequest) (*model.TelegramBotResponse, error)); ok {
		return rf(ctx, clientID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.TelegramBotCreateRequest) *model.TelegramBotResponse); ok {
		r0 = rf(ctx, clientID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TelegramBotResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.TelegramBotCreateRequest) error); ok {
		r1 = rf(ctx, clientID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, clientID, botID
func (_m *ITelegramBotUseCase) Delete(ctx context.Context, clientID uuid.UUID, botID uuid.UUID) error {
	ret := _m.Called(ctx, clientID, botID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, clientID, botID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllByClient provides a mock function with given fields: ctx, clientID
func (_m *ITelegramBotUseCase) FindAllByClient(ctx context.Context, clientID uuid.UUID) ([]model.TelegramBotResponse, error) {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByClient")
	}

	var r0 []model.TelegramBotResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.TelegramBotResponse, error)); ok {
		return rf(ctx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.TelegramBotResponse); ok {
		r0 = rf(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TelegramBotResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, clientID, botID
func (_m *ITelegramBotUseCase) FindByID(ctx context.Context, clientID uuid.UUID, botID uuid.UUID) (*model.TelegramBotResponse, error) {
	ret := _m.Called(ctx, clientID, botID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.TelegramBotResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.TelegramBotResponse, error)); ok {
		return rf(ctx, clientID, botID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.TelegramBotResponse); ok {
		r0 = rf(ctx, clientID, botID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TelegramBotResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, clientID, botID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, clientID, botID, req
func (_m *ITelegramBotUseCase) Update(ctx context.Context, clientID uuid.UUID, botID uuid.UUID, req *model.TelegramBotUpdateRequest) (*model.TelegramBotResponse, error) {
	ret := _m.Called(ctx, clientID, botID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.TelegramBotResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.TelegramBotUpdateRequest) (*model.TelegramBotResponse, error)); ok {
		return rf(ctx, clientID, botID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.TelegramBotUpdateRequest) *model.TelegramBotResponse); ok {
		r0 = rf(ctx, clientID, botID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TelegramBotResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *model.TelegramBotUpdateRequest) error); ok {
		r1 = rf(ctx, clientID, botID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewITelegramBotUseCase creates a new instance of ITelegramBotUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITelegramBotUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITelegramBotUseCase {
	mock := &ITelegramBotUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
