// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ITelegramGroupUseCase is an autogenerated mock type for the ITelegramGroupUseCase type
type ITelegramGroupUseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, clientID, req
func (_m *ITelegramGroupUseCase) Create(ctx context.Context, clientID uuid.UUID, req *model.GroupCreateRequest) (*model.GroupResponse, error) {
	ret := _m.Called(ctx, clientID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.GroupResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.GroupCreateRequest) (*model.GroupResponse, error)); ok {
		return rf(ctx, clientID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.GroupCreateRequest) *model.GroupResponse); ok {
		r0 = rf(ctx, clientID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GroupResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.GroupCreateRequest) error); ok {
		r1 = rf(ctx, clientID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, clientID, groupID
func (_m *ITelegramGroupUseCase) Delete(ctx context.Context, clientID uuid.UUID, groupID uuid.UUID) error {
	ret := _m.Called(ctx, clientID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, clientID, groupID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllByClient provides a mock function with given fields: ctx, clientID
func (_m *ITelegramGroupUseCase) FindAllByClient(ctx context.Context, clientID uuid.UUID) ([]model.GroupResponse, error) {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByClient")
	}

	var r0 []model.GroupResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.GroupResponse, error)); ok {
		return rf(ctx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.GroupResponse); ok {
		r0 = rf(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.GroupResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, clientID, groupID
func (_m *ITelegramGroupUseCase) FindByID(ctx context.Context, clientID uuid.UUID, groupID uuid.UUID) (*model.GroupResponse, error) {
	ret := _m.Called(ctx, clientID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.GroupResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.GroupResponse, error)); ok {
		return rf(ctx, clientID, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.GroupResponse); ok {
		r0 = rf(ctx, clientID, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GroupResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, clientID, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, clientID, groupID, req
func (_m *ITelegramGroupUseCase) Update(ctx context.Context, clientID uuid.UUID, groupID uuid.UUID, req *model.GroupUpdateRequest) (*model.GroupResponse, error) {
	ret := _m.Called(ctx, clientID, groupID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.GroupResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.GroupUpdateRequest) (*model.GroupResponse, error)); ok {
		return rf(ctx, clientID, groupID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.GroupUpdateRequest) *model.GroupResponse); ok {
		r0 = rf(ctx, clientID, groupID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GroupResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *model.GroupUpdateRequest) error); ok {
		r1 = rf(ctx, clientID, groupID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewITelegramGroupUseCase creates a new instance of ITelegramGroupUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITelegramGroupUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITelegramGroupUseCase {
	mock := &ITelegramGroupUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
