// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ITelegramWebhookUseCase is an autogenerated mock type for the ITelegramWebhookUseCase type
type ITelegramWebhookUseCase struct {
	mock.Mock
}

// ProcessUpdate provides a mock function with given fields: ctx, botID, update
func (_m *ITelegramWebhookUseCase) ProcessUpdate(ctx context.Context, botID uuid.UUID, update *tgbotapi.Update) error {
	ret := _m.Called(ctx, botID, update)

	if len(ret) == 0 {
		panic("no return value specified for ProcessUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *tgbotapi.Update) error); ok {
		r0 = rf(ctx, botID, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewITelegramWebhookUseCase creates a new instance of ITelegramWebhookUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITelegramWebhookUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITelegramWebhookUseCase {
	mock := &ITelegramWebhookUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
