// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ITenantAnalyticsUseCase is an autogenerated mock type for the ITenantAnalyticsUseCase type
type ITenantAnalyticsUseCase struct {
	mock.Mock
}

// GetOverview provides a mock function with given fields: ctx, clientID
func (_m *ITenantAnalyticsUseCase) GetOverview(ctx context.Context, clientID uuid.UUID) (*model.TenantAnalyticsOverviewResponse, error) {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for GetOverview")
	}

	var r0 *model.TenantAnalyticsOverviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.TenantAnalyticsOverviewResponse, error)); ok {
		return rf(ctx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.TenantAnalyticsOverviewResponse); ok {
		r0 = rf(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TenantAnalyticsOverviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewITenantAnalyticsUseCase creates a new instance of ITenantAnalyticsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITenantAnalyticsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITenantAnalyticsUseCase {
	mock := &ITenantAnalyticsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
