// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// ITenantTransactionUseCase is an autogenerated mock type for the ITenantTransactionUseCase type
type ITenantTransactionUseCase struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: ctx, clientID, filter
func (_m *ITenantTransactionUseCase) FindAll(ctx context.Context, clientID uuid.UUID, filter model.TransactionFilterRequest) ([]model.TransactionResponse, int64, error) {
	ret := _m.Called(ctx, clientID, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.TransactionResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.TransactionFilterRequest) ([]model.TransactionResponse, int64, error)); ok {
		return rf(ctx, clientID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.TransactionFilterRequest) []model.TransactionResponse); ok {
		r0 = rf(ctx, clientID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.TransactionFilterRequest) int64); ok {
		r1 = rf(ctx, clientID, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, model.TransactionFilterRequest) error); ok {
		r2 = rf(ctx, clientID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewITenantTransactionUseCase creates a new instance of ITenantTransactionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITenantTransactionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITenantTransactionUseCase {
	mock := &ITenantTransactionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
