// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Fadlihardiyanto/telegram-management-app/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// ITenantAuthUseCase is an autogenerated mock type for the ITenantAuthUseCase type
type ITenantAuthUseCase struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, req
func (_m *ITenantAuthUseCase) Login(ctx context.Context, req *model.TenantLoginRequest) (*model.TenantLoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.TenantLoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.TenantLoginRequest) (*model.TenantLoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.TenantLoginRequest) *model.TenantLoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TenantLoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.TenantLoginRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, req
func (_m *ITenantAuthUseCase) Register(ctx context.Context, req *model.TenantRegisterRequest) (*model.TenantRegisterResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *model.TenantRegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.TenantRegisterRequest) (*model.TenantRegisterResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.TenantRegisterRequest) *model.TenantRegisterResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TenantRegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.TenantRegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewITenantAuthUseCase creates a new instance of ITenantAuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITenantAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITenantAuthUseCase {
	mock := &ITenantAuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
