// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"

	time "time"
)

// BotClient is an autogenerated mock type for the BotClient type
type BotClient struct {
	mock.Mock
}

// ApproveChatJoinRequest provides a mock function with given fields: ctx, chatID, userID
func (_m *BotClient) ApproveChatJoinRequest(ctx context.Context, chatID int64, userID int64) error {
	ret := _m.Called(ctx, chatID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ApproveChatJoinRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, chatID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateChatInviteLink provides a mock function with given fields: ctx, chatID, name, createsJoinRequest
func (_m *BotClient) CreateChatInviteLink(ctx context.Context, chatID int64, name string, createsJoinRequest bool) (string, error) {
	ret := _m.Called(ctx, chatID, name, createsJoinRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateChatInviteLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, bool) (string, error)); ok {
		return rf(ctx, chatID, name, createsJoinRequest)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, bool) string); ok {
		r0 = rf(ctx, chatID, name, createsJoinRequest)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, bool) error); ok {
		r1 = rf(ctx, chatID, name, createsJoinRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeclineChatJoinRequest provides a mock function with given fields: ctx, chatID, userID
func (_m *BotClient) DeclineChatJoinRequest(ctx context.Context, chatID int64, userID int64) error {
	ret := _m.Called(ctx, chatID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeclineChatJoinRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, chatID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteWebhook provides a mock function with given fields: ctx
func (_m *BotClient) DeleteWebhook(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBot provides a mock function with no fields
func (_m *BotClient) GetBot() *tgbotapi.BotAPI {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBot")
	}

	var r0 *tgbotapi.BotAPI
	if rf, ok := ret.Get(0).(func() *tgbotapi.BotAPI); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tgbotapi.BotAPI)
		}
	}

	return r0
}

// GetChatMember provides a mock function with given fields: ctx, chatID, userID
func (_m *BotClient) GetChatMember(ctx context.Context, chatID int64, userID int64) (tgbotapi.ChatMember, error) {
	ret := _m.Called(ctx, chatID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetChatMember")
	}

	var r0 tgbotapi.ChatMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (tgbotapi.ChatMember, error)); ok {
		return rf(ctx, chatID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) tgbotapi.ChatMember); ok {
		r0 = rf(ctx, chatID, userID)
	} else {
		r0 = ret.Get(0).(tgbotapi.ChatMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, chatID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWebhookInfo provides a mock function with given fields: ctx
func (_m *BotClient) GetWebhookInfo(ctx context.Context) (tgbotapi.WebhookInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetWebhookInfo")
	}

	var r0 tgbotapi.WebhookInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (tgbotapi.WebhookInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) tgbotapi.WebhookInfo); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(tgbotapi.WebhookInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KickChatMember provides a mock function with given fields: ctx, chatID, userID, untilDate
func (_m *BotClient) KickChatMember(ctx context.Context, chatID int64, userID int64, untilDate time.Time) error {
	ret := _m.Called(ctx, chatID, userID, untilDate)

	if len(ret) == 0 {
		panic("no return value specified for KickChatMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, time.Time) error); ok {
		r0 = rf(ctx, chatID, userID, untilDate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeChatInviteLink provides a mock function with given fields: ctx, chatID, inviteLink
func (_m *BotClient) RevokeChatInviteLink(ctx context.Context, chatID int64, inviteLink string) error {
	ret := _m.Called(ctx, chatID, inviteLink)

	if len(ret) == 0 {
		panic("no return value specified for RevokeChatInviteLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, chatID, inviteLink)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendMessage provides a mock function with given fields: ctx, chatID, text
func (_m *BotClient) SendMessage(ctx context.Context, chatID int64, text string) error {
	ret := _m.Called(ctx, chatID, text)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, chatID, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetWebhook provides a mock function with given fields: ctx, webhookURL, secretToken
func (_m *BotClient) SetWebhook(ctx context.Context, webhookURL string, secretToken string) error {
	ret := _m.Called(ctx, webhookURL, secretToken)

	if len(ret) == 0 {
		panic("no return value specified for SetWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, webhookURL, secretToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnbanChatMember provides a mock function with given fields: ctx, chatID, userID, onlyIfBanned
func (_m *BotClient) UnbanChatMember(ctx context.Context, chatID int64, userID int64, onlyIfBanned bool) error {
	ret := _m.Called(ctx, chatID, userID, onlyIfBanned)

	if len(ret) == 0 {
		panic("no return value specified for UnbanChatMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, bool) error); ok {
		r0 = rf(ctx, chatID, userID, onlyIfBanned)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBotClient creates a new instance of BotClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBotClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BotClient {
	mock := &BotClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
