// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	telegram "github.com/Fadlihardiyanto/telegram-management-app/pkg/telegram"
	mock "github.com/stretchr/testify/mock"
)

// BotFactory is an autogenerated mock type for the BotFactory type
type BotFactory struct {
	mock.Mock
}

// NewClient provides a mock function with given fields: token
func (_m *BotFactory) NewClient(token string) (telegram.BotClient, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for NewClient")
	}

	var r0 telegram.BotClient
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (telegram.BotClient, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) telegram.BotClient); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(telegram.BotClient)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBotFactory creates a new instance of BotFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBotFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *BotFactory {
	mock := &BotFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
